LOCATION_MAPPING = {
    [430001] = {"@Annwfn/Kujata/Kujata Reward"}, -- [ANN F-2] Kujata Reward
    [430002] = {"@Immortal Battlefield/Jormungand/Jormungand Reward"}, -- [IB E-5] Jormungand Reward
    [430004] = {"@Immortal Battlefield/Buried Fortress Chest/Chest"}, -- [IB H-7] Buried Fortress Chest
    [430005] = {"@Immortal Battlefield/Time Altar Chest/Chest"}, -- [IB B-4] Time Altar Chest
    [430006] = {"@Shrine of the Frost Giants/Badhbh Cath Reward/Chest"}, -- [SFG E-3] Badhbh Cath Reward
    [430007] = {"@Roots of Yggdrasil/Golden Rock Chest/Chest"}, -- [ROY E-6] Golden Rock Chest
    [430009] = {"@Dark Star Lords Mausoleum/Ammit Reward/Chest"}, -- [DSLM B-1] Ammit Reward
    [430011] = {"@Takamagahara Shrine/Daji Reward/Chest"}, -- [TS E-6] Daji Reward
    [430012] = {"@Hall of Malice/Echidna/Echidna Reward"}, -- [HOM C-5] Echidna Reward
    [430013] = {"@Heavens Labyrinth/Battery Chest/Chest"}, -- [HL A-5] Battery Chest
    [430015] = {"@Heavens Labyrinth/Heaven's Labyrinth Tent Item/FreeStanding"}, -- [HL D-1] Heaven's Labyrinth Tent Item
    [430016] = {"@La-Mulana/Shell Horn Chest/Chest"}, -- [GOG D-2] Shell Horn Chest
    [430017] = {"@La-Mulana/Holy Grail Chest/Chest"}, -- [GOG B-4] Holy Grail Chest
    [430018] = {"@Icefire Treetop/Lower Statue Chest/Chest"}, -- [IT E-1] Lower Statue Chest
    [430019] = {"@Annwfn/Look Away Chest/Chest"}, -- [ANN C-4] Look Away Chest
    [430020] = {"@Immortal Battlefield/Dinosaur Figure Chest/Chest"}, -- [IB I-7] Dinosaur Figure Chest
    [430021] = {"@Immortal Battlefield/Fake Wall Chest/Chest"}, -- [IB B-2] Fake Wall Chest
    [430022] = {"@Icefire Treetop/Surtr/Surtr Reward"}, -- [IT C-2] Surtr Reward
    [430023] = {"@Gate of the Dead/Laser Beams Chest/Chest"}, -- [GOTD C-7] Laser Beams Chest
    [430024] = {"@Takamagahara Shrine/Belial Reward/Chest"}, -- [TS A-2] Belial Reward
    [430025] = {"@La-Mulana/Hidden Item Spot/FreeStanding"}, -- [GOG B-4] Hidden Item Spot
    [430026] = {"@Heavens Labyrinth/Griffin Reward/Chest"}, -- [HL E-2] Griffin Reward
    [430027] = {"@Immortal Battlefield/Hidden Sigil Chest/Chest"}, -- [IB G-5] Hidden Sigil Chest
    [430028] = {"@Hall of Malice/Time Puzzle Chest/Chest"}, -- [HOM A-4] Time Puzzle Chest
    [430029] = {"@Shrine of the Frost Giants/Top-Left Breakable Ceiling/Chest"}, -- [SFG A-3] Top-Left Breakable Ceiling
    [430030] = {"@Gate of the Dead/Dwarves' Missing Block Chest/Chest"}, -- [GOTD B-6] Dwarves' Missing Block Chest
    [430032] = {"@Immortal Battlefield/Top Dash Chest/Chest"}, -- [IB D-2] Top Dash Chest
    [430033] = {"@Icefire Treetop/Skull in Background Chest/Chest"}, -- [IT E-4] Skull in Background Chest
    [430034] = {"@Eternal Prison - Doom/Spaulder Key Fairy Chest/Chest"}, -- [EPD C-2] Spaulder Key Fairy Chest
    [430035] = {"@Valhalla/Vritra/Vritra Reward"}, -- [VAL E-2] Vritra Reward
    [430036] = {"@Dark Star Lords Mausoleum/Aten Ra/Aten-Ra Reward"}, -- [DSLM C-8] Aten-Ra Reward
    [430038] = {"@Dark Star Lords Mausoleum/Zero Weight Scale Chest/Chest"}, -- [DSLM B-7] Zero Weight Scale Chest
    [430039] = {"@Takamagahara Shrine/Key Fairy Chest/Chest"}, -- [TS B-4] Key Fairy Chest
    [430041] = {"@Dark Star Lords Mausoleum/Destroy the False Tablet/Chest"}, -- [DSLM A-4] Destroy the False Tablet
    [430042] = {"@Ancient Chaos/Anu/Anu Reward"}, -- [AC D-1] Anu Reward
    [430043] = {"@Divine Fortress/Frey's Ship/FreeStanding"}, -- [DF D-3] Frey's Ship
    [430047] = {"@Eternal Prison - Doom/Hel/Hel Reward"}, -- [EPD A-3] Hel Reward
    [430049] = {"@Ancient Chaos/Anzu Reward/Chest"}, -- [AC D-2] Anzu Reward
    [430050] = {"@Altar/Secret Treasure of Life Location/FreeStanding"}, -- [ALTAR] Secret Treasure of Life Location
    [430051] = {"@Divine Fortress/Hugin & Munin Reward/Chest"}, -- [DF E-3] Hugin & Munin Reward
    [430052] = {"@Shrine of the Frost Giants/7 Dais Chest/Chest"}, -- [SFG E-7] 7 Dais Chest
    [430053] = {"@Icefire Treetop/Arrow Trap Chest/Chest"}, -- [IT A-2] Arrow Trap Chest
    [430054] = {"@Eternal Prison - Gloom/Ajisukitakahikone Reward/Chest"}, -- [EPD C-3] Ajisukitakahikone Reward
    [430056] = {"@Shrine of the Frost Giants/Balor Reward/Chest"}, -- [SFG D-1] Balor Reward
    [430063] = {"@Roots of Yggdrasil/Knife Weapon Vault/FreeStanding"}, -- [ROY B-2] Knife Weapon Vault
    [430064] = {"@Shrine of the Frost Giants/Rapier Weapon Vault/FreeStanding"}, -- [SFG B-5] Rapier Weapon Vault
    [430065] = {"@Heavens Labyrinth/Heaven's Labyrinth Weapon Vault/FreeStanding"}, -- [HL B-1] Heaven's Labyrinth Weapon Vault
    [430066] = {"@Gate of the Dead/GotD Weapon Vault/FreeStanding"}, -- [GOTD B-2] GotD Weapon Vault
    [430067] = {"@Roots of Yggdrasil/Shuriken Weapon Vault/FreeStanding"}, -- [ROY C-3] Shuriken Weapon Vault
    [430068] = {"@Annwfn/Annwfn Weapon Vault/FreeStanding"}, -- [ANN C-1] Annwfn Weapon Vault
    [430069] = {"@Immortal Battlefield/Top-Left Weapon Vault/FreeStanding"}, -- [IB C-1] Top-Left Weapon Vault
    [430070] = {"@Takamagahara Shrine/Flare Gun Weapon Vault/FreeStanding"}, -- [TS F-3] Flare Gun Weapon Vault
    [430071] = {"@Eternal Prison - Gloom/Key-locked Weapon Vault/FreeStanding"}, -- [EPG C-6] Key-locked Weapon Vault
    [430072] = {"@Immortal Battlefield/Pressure Plate Weapon Vault/FreeStanding"}, -- [IB I-6] Pressure Plate Weapon Vault
    [430073] = {"@Valhalla/Crawling Weapon Vault/FreeStanding"}, -- [VAL C-4] Crawling Weapon Vault
    [430079] = {"@Gate of the Dead/Flipped Push Block Chest/Chest"}, -- [GOTD E-3] Flipped Push Block Chest
    [430082] = {"@Roots of Yggdrasil/Mantra Software Mural/Mural"}, -- [ROY D-2] Mantra Software Mural
    [430086] = {"@Eternal Prison - Gloom/Beo Eg-Lana Mural/Mural"}, -- [EPG E-7] Beo Eg-Lana Mural
    [430091] = {"@Divine Fortress/Breakable Push Block Chest/Chest"}, -- [DF C-2] Breakable Push Block Chest
    [430097] = {"@Hall of Malice/Flame Torc Breakable Wall Chest/Chest"}, -- [HOM E-5] Flame Torc Breakable Wall Chest
    [430099] = {"@Dark Star Lords Mausoleum/Bombable Wall Chest/Chest"}, -- [DSLM C-3] Bombable Wall Chest
    [430100] = {"@Eternal Prison - Doom/Top-Left Mjolnir Switch Chest/Chest"}, -- [EPD D-4] Top-Left Mjolnir Switch Chest
    [430101] = {"@La-Mulana/Waterfall Sacred Orb/FreeStanding"}, -- [VOD G-3] Waterfall Sacred Orb
    [430102] = {"@Roots of Yggdrasil/Sacred Orb Chest/Chest"}, -- [ROY E-4] Sacred Orb Chest
    [430103] = {"@Annwfn/Hidden Chest & Sigil/Chest"}, -- [ANN E-5] Hidden Chest & Sigil
    [430104] = {"@Immortal Battlefield/Submerged Sigil Chest/Chest"}, -- [IB F-6] Submerged Sigil Chest
    [430105] = {"@Icefire Treetop/Sunken Chest/Chest"}, -- [IT F-4] Sunken Chest
    [430106] = {"@Divine Fortress/5 Weights Chest/Chest"}, -- [DF A-4] 5 Weights Chest
    [430107] = {"@Shrine of the Frost Giants/Mimic Chest Mimic/Chest"}, -- [SFG C-2] Mimic Chest Mimic
    [430108] = {"@Gate of the Dead/Mirrored Dais & Chest/Chest"}, -- [GOTD B-4] Mirrored Dais & Chest
    [430109] = {"@Takamagahara Shrine/Falling Platform Chest/Chest"}, -- [TS D-5] Falling Platform Chest
    [430110] = {"@Heavens Labyrinth/Middle Top Chest/Chest"}, -- [HL C-2] Middle Top Chest
    [430111] = {"@Roots of Yggdrasil/Map Chest/Chest"}, -- [ROY E-3] Map Chest
    [430112] = {"@Annwfn/Map Chest/Chest"}, -- [ANN E-3] Map Chest
    [430113] = {"@Immortal Battlefield/Map Chest/Chest"}, -- [IB F-2] Map Chest
    [430114] = {"@Icefire Treetop/Map Chest/Chest"}, -- [IT B-2] Map Chest
    [430115] = {"@Divine Fortress/Map Chest/Chest"}, -- [DF D-4] Map Chest
    [430116] = {"@Shrine of the Frost Giants/Map Chest/Chest"}, -- [SFG D-5] Map Chest
    [430117] = {"@Gate of the Dead/Map Chest/Chest"}, -- [GOTD D-3] Map Chest
    [430118] = {"@Takamagahara Shrine/Map Chest/Chest"}, -- [TS D-2] Map Chest
    [430119] = {"@Heavens Labyrinth/Map Chest/Chest"}, -- [HL C-5] Map Chest
    [430120] = {"@Valhalla/Map Chest/Chest"}, -- [VAL A-3] Map Chest
    [430121] = {"@Dark Star Lords Mausoleum/Map Chest/Chest"}, -- [DSLM C-6] Map Chest
    [430122] = {"@Ancient Chaos/Map Chest/Chest"}, -- [AC B-6] Map Chest
    [430123] = {"@Hall of Malice/Map Chest/Chest"}, -- [HOM C-1] Map Chest
    [430124] = {"@Eternal Prison - Gloom/Map Chest/Chest"}, -- [EPG E-2] Map Chest
    [430125] = {"@Eternal Prison - Doom/Map Chest/Chest"}, -- [EPD D-5] Map Chest
    [430132] = {"@Roots of Yggdrasil/Ankh Chest/Chest"}, -- [ROY B-3] Ankh Chest
    [430133] = {"@Divine Fortress/Ankh Chest/Chest"}, -- [DF A-4] Ankh Chest
    [430134] = {"@Icefire Treetop/Vedfolnir Reward/Chest"}, -- [IT B-4] Vedfolnir Reward
    [430135] = {"@Shrine of the Frost Giants/3 Timed Weights Chest/Chest"}, -- [SFG B-6] 3 Timed Weights Chest
    [430136] = {"@Dark Star Lords Mausoleum/Top-Right Grapple Chest/Chest"}, -- [DSLM E-3] Top-Right Grapple Chest
    [430137] = {"@Ancient Chaos/There is Nothing Here/Chest"}, -- [AC A-4] There is Nothing Here
    [430139] = {"@Eternal Prison - Gloom/Ratatoskr 4 Reward/FreeStanding"}, -- [EPG A-5] Ratatoskr 4 Reward
    [430140] = {"@Roots of Yggdrasil/Fafnir/Fafnir Reward"}, -- [ROY F-3] Fafnir Boss Reward
    [430141] = {"@Annwfn/Submerged Chest/Chest"}, -- [ANN B-5] Submerged Chest
    [430142] = {"@Immortal Battlefield/Ratatoskr 2 Reward/FreeStanding"}, -- [IB C-3] Ratatoskr 2 Reward
    [430143] = {"@Icefire Treetop/Ratatoskr 3 Reward/Chest"}, -- [IT G-2] Ratatoskr 3 Reward
    [430144] = {"@Valhalla/Jalandhara's Treasure/Chest"}, -- [VAL B-5] Jalandhara's Treasure
    [430145] = {"@Gate of the Dead/Flipped Crusher Chest/Chest"}, -- [GOTD F-3] Flipped Crusher Chest
    [430146] = {"@Takamagahara Shrine/4 Moving Platforms Chest/Chest"}, -- [TS C-6] 4 Moving Platforms Chest
    [430147] = {"@Dark Star Lords Mausoleum/Use Crystal Skull Chest/Chest"}, -- [DSLM B-3] Use Crystal Skull Chest
    [430148] = {"@Ancient Chaos/Simultaneous Strike Chest/Chest"}, -- [AC B-5] Simultaneous Strike Chest
    [430149] = {"@Heavens Labyrinth/Hidden Dais Chest/Chest"}, -- [HL A-2] Hidden Dais Chest
    [430150] = {"@Hall of Malice/Chest Behind Ladon/Chest"}, -- [HOM F-3] Chest Behind Ladon
    [430151] = {"@Eternal Prison - Doom/Lava Maze Chest/Chest"}, -- [EPD A-4] Lava Maze Chest
    [430153] = {"@Immortal Battlefield/Lava Weapon Vault/FreeStanding"}, -- [IB C-6] Lava Weapon Vault
    [430154] = {"@Valhalla/4 Sigil Weapon Vault/FreeStanding"}, -- [VAL D-2] 4 Sigil Weapon Vault
    [430156] = {"@Annwfn/Mimir Weapon Vault/FreeStanding"}, -- [ANN F-5] Mimir Weapon Vault
    [430157] = {"@Divine Fortress/Heaven Mantra Mural/Mural"}, -- [DF D-5] Heaven Mantra Mural
    [430158] = {"@Annwfn/Earth Mantra Mural/Mural"}, -- [ANN D-4] Earth Mantra Mural
    [430159] = {"@Cavern/Sun Mantra Mural/Mural"}, -- [CAVERN] Sun Mantra Mural
    [430160] = {"@Immortal Battlefield/Moon Mantra Mural/Mural"}, -- [IB E-7] Moon Mantra Mural
    [430161] = {"@Shrine of the Frost Giants/Sea Mantra Mural/Mural"}, -- [SFG C-3] Sea Mantra Mural
    [430162] = {"@Valhalla/Fire Mantra Mural/Mural"}, -- [VAL D-1] Fire Mantra Mural
    [430163] = {"@Ancient Chaos/Wind Mantra Mural/Mural"}, -- [AC D-5] Wind Mantra Mural
    [430164] = {"@Eternal Prison - Gloom/Mother Mantra Mural/Mural"}, -- [EPG C-5] Mother Mantra Mural
    [430165] = {"@La-Mulana/Child Mantra Mural/Mural"}, -- [IC A-1] Child Mantra Mural
    [430166] = {"@Nibiru/Night Mantra Mural/Mural"}, -- [NIBIRU] Night Mantra Mural
    [430167] = {"@Annwfn/Annwfn Research Papers/FreeStanding"}, -- [ANN C-2] Annwfn Research Papers
    [430168] = {"@Icefire Treetop/IT Research Papers/FreeStanding"}, -- [IT E-3] IT Research Papers
    [430169] = {"@Immortal Battlefield/IB Research - Top Left/FreeStanding"}, -- [IB D-1] IB Research - Top Left
    [430170] = {"@Immortal Battlefield/IB Research - Top Right/FreeStanding"}, -- [IB G-1] IB Research - Top Right
    [430171] = {"@Immortal Battlefield/IB Research - Left Chamber/FreeStanding"}, -- [IB A-6] IB Research - Left Chamber
    [430172] = {"@Immortal Battlefield/IB Research - Pit of Time/FreeStanding"}, -- [IB C-5] IB Research - Pit of Time
    [430173] = {"@Immortal Battlefield/Immortal Battlefield Tent/IB Research - Tent (First Time)"}, -- [IB E-3] IB Research - Tent (First Time)
    [430174] = {"@Immortal Battlefield/Immortal Battlefield Tent/IB Research - Tent (7 Guardians)"}, -- [IB E-3] IB Research - Tent (7 Guardians)
    [430175] = {"@Immortal Battlefield/Immortal Battlefield Tent/IB Research - Tent (Post Heimdall)"}, -- [IB E-3] IB Research - Tent (Post Heimdall)
    [430176] = {"@Dark Star Lords Mausoleum/DSLM Research Papers/FreeStanding"}, -- [DSLM A-4] DSLM Research Papers
    [430177] = {"@Valhalla/Vritra/Vritra's Dissonance"}, -- [VAL E-3] Vritra's Dissonance
    [430178] = {"@Dark Star Lords Mausoleum/Aten Ra/Aten-Ra's Dissonance"}, -- [DSLM C-8] Aten-Ra's Dissonance
    [430179] = {"@Heavens Labyrinth/Typhon's Dissonance/Dissonance"}, -- [HL C-4] Typhon's Dissonance
    [430180] = {"@Eternal Prison - Doom/Hel/Hel's Dissonance"}, -- [EPD A-3] Hel's Dissonance
    [430181] = {"@Nibiru/Nibiru's Dissonance/Dissonance"}, -- [NIBIRU] Nibiru's Dissonance
    [430182] = {"@La-Mulana/Sakit's Dissonance/Dissonance"}, -- [MOG E-4] Sakit's Dissonance
    [430183] = {"@La-Mulana/Alsedana's Item (Vritra)/Dialogue"}, -- [VOD B-3] Alsedana's Item (Vritra)
    [430184] = {"@La-Mulana/Alsedana's Funeral (6 Guardians)/Dialogue"}, -- [VOD B-3] Alsedana's Funeral (6 Guardians)
    [430185] = {"@La-Mulana/Xelpud's Item/Dialogue"}, -- [VOD D-4] Xelpud's Item
    [430186] = {"@La-Mulana/Nebur's Item/Dialogue"}, -- [VOD E-4] Nebur's Item
    [430187] = {"@La-Mulana/Freya's Item/Dialogue"}, -- [EC A-1] Freya's Item
    [430188] = {"@La-Mulana/Fobos/Fobos' Inspiration"}, -- [GOI C-3] Fobos' Inspiration
    [430189] = {"@La-Mulana/Fobos/Fobos' Skull Check"}, -- [GOI C-3] Fobos' Skull Check
    [430190] = {"@Immortal Battlefield/Mulbruk's Item (4 Guardians)/Dialogue"}, -- [IB G-3] Mulbruk's Item (4 Guardians)
    [430191] = {"@Eternal Prison - Doom/Anubis Trials/Dialogue"}, -- [EPD C-5] Anubis Trials
    [430192] = {"@La-Mulana/Nebur/Shop Slot 1"}, -- [VOD C-4] Nebur Shop 1
    [430193] = {"@La-Mulana/Nebur/Shop Slot 2"}, -- [VOD C-4] Nebur Shop 2
    [430194] = {"@La-Mulana/Nebur/Shop Slot 3"}, -- [VOD C-4] Nebur Shop 3
    [430195] = {"@La-Mulana/Modro/Shop Slot 1"}, -- [VOD E-4] Modro Shop 1
    [430196] = {"@La-Mulana/Modro/Shop Slot 2"}, -- [VOD E-4] Modro Shop 2
    [430197] = {"@La-Mulana/Modro/Shop Slot 3"}, -- [VOD E-4] Modro Shop 3
    [430198] = {"@La-Mulana/Sidro/Shop Slot 1"}, -- [VOD E-4] Sidro Shop 1
    [430199] = {"@La-Mulana/Sidro/Shop Slot 2"}, -- [VOD E-4] Sidro Shop 2
    [430200] = {"@La-Mulana/Sidro/Shop Slot 3"}, -- [VOD E-4] Sidro Shop 3
    [430201] = {"@La-Mulana/Hiner/Shop Slot 1"}, -- [GOG B-4] Hiner Shop 1
    [430202] = {"@La-Mulana/Hiner/Shop Slot 2"}, -- [GOG B-4] Hiner Shop 2
    [430203] = {"@La-Mulana/Hiner/Shop Slot 3"}, -- [GOG B-4] Hiner Shop 3
    [430204] = {"@La-Mulana/Hiner/Shop Slot 4"}, -- [GOG B-4] Hiner Shop 4 (3 Guardians)
    [430205] = {"@Roots of Yggdrasil/Korobock/Shop Slot 1"}, -- [ROY C-5] Korobock Shop 1
    [430206] = {"@Roots of Yggdrasil/Korobock/Shop Slot 2"}, -- [ROY C-5] Korobock Shop 2
    [430207] = {"@Roots of Yggdrasil/Korobock/Shop Slot 3"}, -- [ROY C-5] Korobock Shop 3
    [430208] = {"@Divine Fortress/Shuhoka/Shop Slot 1"}, -- [DF B-5] Shuhoka Shop 1
    [430209] = {"@Divine Fortress/Shuhoka/Shop Slot 2"}, -- [DF B-5] Shuhoka Shop 2
    [430210] = {"@Divine Fortress/Shuhoka/Shop Slot 3"}, -- [DF B-5] Shuhoka Shop 3
    [430211] = {"@Annwfn/Pym/Shop Slot 1"}, -- [ANN E-1] Pym Shop 1
    [430212] = {"@Annwfn/Pym/Shop Slot 2"}, -- [ANN E-1] Pym Shop 2
    [430213] = {"@Annwfn/Pym/Shop Slot 3"}, -- [ANN E-1] Pym Shop 3
    [430214] = {"@Icefire Treetop/BTK/Shop Slot 1"}, -- [IT A-1] BTK Shop 1
    [430215] = {"@Icefire Treetop/BTK/Shop Slot 2"}, -- [IT A-1] BTK Shop 2
    [430216] = {"@Icefire Treetop/BTK/Shop Slot 3"}, -- [IT A-1] BTK Shop 3
    [430217] = {"@Icefire Treetop/Mino the Bomb Guy/Shop Slot 1"}, -- [IT C-4] Mino Shop 1
    [430218] = {"@Icefire Treetop/Mino the Bomb Guy/Shop Slot 2"}, -- [IT C-4] Mino Shop 2
    [430219] = {"@Icefire Treetop/Mino the Bomb Guy/Shop Slot 3"}, -- [IT C-4] Mino Shop 3
    [430220] = {"@Valhalla/Bargain Duck/Shop Slot 1"}, -- [VAL D-4] Bargain Duck Shop 1
    [430221] = {"@Valhalla/Bargain Duck/Shop Slot 2"}, -- [VAL D-4] Bargain Duck Shop 2
    [430222] = {"@Valhalla/Bargain Duck/Shop Slot 3"}, -- [VAL D-4] Bargain Duck Shop 3
    [430223] = {"@Ancient Chaos/Venum/Shop Slot 1"}, -- [AC C-6] Venum Shop 1
    [430224] = {"@Ancient Chaos/Venum/Shop Slot 2"}, -- [AC C-6] Venum Shop 2
    [430225] = {"@Ancient Chaos/Venum/Shop Slot 3"}, -- [AC C-6] Venum Shop 3
    [430226] = {"@Immortal Battlefield/Peibalusa/Shop Slot 1"}, -- [IB E-1] Peibalusa Shop 1
    [430227] = {"@Immortal Battlefield/Peibalusa/Shop Slot 2"}, -- [IB E-1] Peibalusa Shop 2
    [430228] = {"@Immortal Battlefield/Peibalusa/Shop Slot 3"}, -- [IB E-1] Peibalusa Shop 3
    [430229] = {"@Immortal Battlefield/Hiro Roderick/Shop Slot 1"}, -- [IB G-6] Hiro Roderick Shop 1
    [430230] = {"@Immortal Battlefield/Hiro Roderick/Shop Slot 2"}, -- [IB G-6] Hiro Roderick Shop 2
    [430231] = {"@Immortal Battlefield/Hiro Roderick/Shop Slot 3"}, -- [IB G-6] Hiro Roderick Shop 3
    [430232] = {"@Shrine of the Frost Giants/Hydlit/Shop Slot 1"}, -- [SFG A-5] Hydlit Shop 1
    [430233] = {"@Shrine of the Frost Giants/Hydlit/Shop Slot 2"}, -- [SFG A-5] Hydlit Shop 2
    [430234] = {"@Shrine of the Frost Giants/Hydlit/Shop Slot 3"}, -- [SFG A-5] Hydlit Shop 3
    [430235] = {"@Gate of the Dead/Aytum/Shop Slot 1"}, -- [GOTD B-3] Aytum Shop 1
    [430236] = {"@Gate of the Dead/Aytum/Shop Slot 2"}, -- [GOTD B-3] Aytum Shop 2
    [430237] = {"@Gate of the Dead/Aytum/Shop Slot 3"}, -- [GOTD B-3] Aytum Shop 3
    [430238] = {"@Dark Star Lords Mausoleum/Kero/Shop Slot 1"}, -- [DSLM C-2] Kero Shop 1
    [430239] = {"@Dark Star Lords Mausoleum/Kero/Shop Slot 2"}, -- [DSLM C-2] Kero Shop 2
    [430240] = {"@Dark Star Lords Mausoleum/Kero/Shop Slot 3"}, -- [DSLM C-2] Kero Shop 3
    [430241] = {"@Takamagahara Shrine/Ash Geen/Shop Slot 1"}, -- [TS C-4] Ash Geen Shop 1
    [430242] = {"@Takamagahara Shrine/Ash Geen/Shop Slot 2"}, -- [TS C-4] Ash Geen Shop 2
    [430243] = {"@Takamagahara Shrine/Ash Geen/Shop Slot 3"}, -- [TS C-4] Ash Geen Shop 3
    [430244] = {"@Hall of Malice/Fairylan/Shop Slot 1"}, -- [HOM G-4] Fairylan Shop 1
    [430245] = {"@Hall of Malice/Fairylan/Shop Slot 2"}, -- [HOM G-4] Fairylan Shop 2
    [430246] = {"@Hall of Malice/Fairylan/Shop Slot 3"}, -- [HOM G-4] Fairylan Shop 3
    [430247] = {"@Heavens Labyrinth/Megarock/Shop Slot 1"}, -- [HL A-3] Megarock Shop 1
    [430248] = {"@Heavens Labyrinth/Megarock/Shop Slot 2"}, -- [HL A-3] Megarock Shop 2
    [430249] = {"@Heavens Labyrinth/Megarock/Shop Slot 3"}, -- [HL A-3] Megarock Shop 3
    [430250] = { -- [RANDO] Starting Shop 1
        "@Starting Shop RoY/Shop Slot 1", "@Starting Shop Ann/Shop Slot 1",
        "@Starting Shop IB/Shop Slot 1", "@Starting Shop IT/Shop Slot 1",
        "@Starting Shop DF/Shop Slot 1", "@Starting Shop SFG/Shop Slot 1",
        "@Starting Shop TS/Shop Slot 1", "@Starting Shop Val/Shop Slot 1",
        "@Starting Shop DSLM/Shop Slot 1", "@Starting Shop AC/Shop Slot 1",
        "@Starting Shop HoM/Shop Slot 1"
    },
    [430251] = { -- [RANDO] Starting Shop 2
        "@Starting Shop RoY/Shop Slot 2", "@Starting Shop Ann/Shop Slot 2",
        "@Starting Shop IB/Shop Slot 2", "@Starting Shop IT/Shop Slot 2",
        "@Starting Shop DF/Shop Slot 2", "@Starting Shop SFG/Shop Slot 2",
        "@Starting Shop TS/Shop Slot 2", "@Starting Shop Val/Shop Slot 2",
        "@Starting Shop DSLM/Shop Slot 2", "@Starting Shop AC/Shop Slot 2",
        "@Starting Shop HoM/Shop Slot 2"
    },
    [430252] = { -- [RANDO] Starting Shop 3
        "@Starting Shop RoY/Shop Slot 3", "@Starting Shop Ann/Shop Slot 3",
        "@Starting Shop IB/Shop Slot 3", "@Starting Shop IT/Shop Slot 3",
        "@Starting Shop DF/Shop Slot 3", "@Starting Shop SFG/Shop Slot 3",
        "@Starting Shop TS/Shop Slot 3", "@Starting Shop Val/Shop Slot 3",
        "@Starting Shop DSLM/Shop Slot 3", "@Starting Shop AC/Shop Slot 3",
        "@Starting Shop HoM/Shop Slot 3"
    },
    -- Pots (potsanity)
    [430400] = {"@La-Mulana/Starting Coin Pot/Pot", "@Potsanity - La-Mulana (1)/Starting Coin Pot"}, -- [START] Starting Coin Pot
    [430401] = {"@La-Mulana/Alsedana Coin Pot/Pot", "@Potsanity - La-Mulana (1)/Alsedana Coin Pot"}, -- [VOD B-3] Alsedana Coin Pot
    [430402] = {"@La-Mulana/Nebur Coin Pot/Pot", "@Potsanity - La-Mulana (1)/Nebur Coin Pot"}, -- [VOD C-4] Nebur Coin Pot
    [430403] = {"@La-Mulana/Xelpud Coin Pot/Pot", "@Potsanity - La-Mulana (1)/Xelpud Coin Pot"}, -- [VOD D-4] Xelpud Coin Pot
    [430404] = {"@La-Mulana/Xelpud Weight Pot/Pot", "@Potsanity - La-Mulana (1)/Xelpud Weight Pot"}, -- [VOD D-4] Xelpud Weight Pot
    [430405] = {"@La-Mulana/Pre-Ladder Weight Pot/Pot", "@Potsanity - La-Mulana (2)/Pre-Ladder Weight Pot"}, -- [VOD E-4] Pre-Ladder Weight Pot
    [430406] = {"@La-Mulana/Post-Ladder Coin Pot/Pot", "@Potsanity - La-Mulana (2)/Post-Ladder Coin Pot"}, -- [VOD E-3] Post-Ladder Coin Pot
    [430407] = {"@La-Mulana/Double Jump Item Pot/Pot", "@Potsanity - La-Mulana (2)/Double Jump Item Pot"}, -- [VOD E-3] Double Jump Item Pot
    [430408] = {"@La-Mulana/Photo Stand-in Weight Pot/Pot", "@Potsanity - La-Mulana (2)/Photo Stand-in Weight Pot"}, -- [GOG C-2] Photo Stand-in Weight Pot
    [430409] = {"@La-Mulana/High-up Coin Pot/Pot", "@Potsanity - La-Mulana (2)/High-up Coin Pot"}, -- [GOG C-3] High-up Coin Pot
    [430410] = {"@La-Mulana/Below Hiner Coin Pot/Pot", "@Potsanity - La-Mulana (3)/Below Hiner Coin Pot"}, -- [GOG B-5] Below Hiner Coin Pot
    [430411] = {"@La-Mulana/Illusion Gate Item Pot/Pot", "@Potsanity - La-Mulana (3)/Illusion Gate Item Pot"}, -- [GOG A-3] Illusion Gate Item Pot
    [430412] = {"@La-Mulana/First Room Coin Pot/Pot", "@Potsanity - La-Mulana (3)/First Room Coin Pot"}, -- [MOG A-1] First Room Coin Pot
    [430413] = {"@La-Mulana/Second Room Weight Pot/Pot", "@Potsanity - La-Mulana (3)/Second Room Weight Pot"}, -- [MOG B-1] Second Room Weight Pot
    [430414] = {"@La-Mulana/Breakable Wall Coin Pot/Pot", "@Potsanity - La-Mulana (3)/Breakable Wall Coin Pot"}, -- [MOG A-2] Breakable Wall Coin Pot
    [430415] = {"@La-Mulana/Futo Statue Coin Pot/Pot", "@Potsanity - La-Mulana (4)/Futo Statue Coin Pot"}, -- [MOG D-4] Futo Statue Coin Pot
    [430416] = {"@La-Mulana/Pre-Ratatoskr Weight Pot/Pot", "@Potsanity - La-Mulana (4)/Pre-Ratatoskr Weight Pot"}, -- [MOG C-5] Pre-Ratatoskr Weight Pot
    [430417] = {"@Roots of Yggdrasil/Second Room Weight Pot/Pot", "@Potsanity - Roots of Yggdrasil (1)/Second Room Weight Pot"}, -- [ROY E-3] Second Room Weight Pot
    [430418] = {"@Roots of Yggdrasil/Weapon Vault Coin Pot/Pot", "@Potsanity - Roots of Yggdrasil (1)/Weapon Vault Coin Pot"}, -- [ROY C-3] Weapon Vault Coin Pot
    [430419] = {"@Roots of Yggdrasil/Weapon Vault Weight Pot/Pot", "@Potsanity - Roots of Yggdrasil (1)/Weapon Vault Weight Pot"}, -- [ROY C-3] Weapon Vault Weight Pot
    [430420] = {"@Roots of Yggdrasil/Convenient Item Pot/Pot", "@Potsanity - Roots of Yggdrasil (1)/Convenient Item Pot"}, -- [ROY B-3] Convenient Item Pot
    [430421] = {"@Roots of Yggdrasil/Below Ratatoskr Coin Pot/Pot", "@Potsanity - Roots of Yggdrasil (1)/Below Ratatoskr Coin Pot"}, -- [ROY B-2] Below Ratatoskr Coin Pot
    [430422] = {"@Roots of Yggdrasil/Footprint Item Pot/Pot", "@Potsanity - Roots of Yggdrasil (2)/Footprint Item Pot"}, -- [ROY C-2] Footprint Item Pot
    [430423] = {"@Roots of Yggdrasil/Bridge Coin Pot/Pot", "@Potsanity - Roots of Yggdrasil (2)/Bridge Coin Pot"}, -- [ROY E-2] Bridge Coin Pot
    [430424] = {"@Roots of Yggdrasil/Birth Seal Gate Item Pot/Pot", "@Potsanity - Roots of Yggdrasil (2)/Birth Seal Gate Item Pot"}, -- [ROY G-1] Birth Seal Gate Item Pot
    [430425] = {"@Roots of Yggdrasil/First Room Coin Pot/Pot", "@Potsanity - Roots of Yggdrasil (2)/First Room Coin Pot"}, -- [ROY E-4] First Room Coin Pot
    [430426] = {"@Roots of Yggdrasil/Large Breakable Wall Coin Pot/Pot", "@Potsanity - Roots of Yggdrasil (2)/Large Breakable Wall Coin Pot"}, -- [ROY C-4] Large Breakable Wall Coin Pot
    [430427] = {"@Roots of Yggdrasil/Korobock Weight Pot/Pot", "@Potsanity - Roots of Yggdrasil (3)/Korobock Weight Pot"}, -- [ROY C-5] Korobock Weight Pot
    [430428] = {"@Roots of Yggdrasil/Candlestick of Time Weight Pot/Pot", "@Potsanity - Roots of Yggdrasil (3)/Candlestick of Time Weight Pot"}, -- [ROY D-5] Candlestick of Time Weight Pot
    [430429] = {"@Roots of Yggdrasil/Torch Room Item Pot/Pot", "@Potsanity - Roots of Yggdrasil (3)/Torch Room Item Pot"}, -- [ROY E-5] Torch Room Item Pot
    [430430] = {"@Roots of Yggdrasil/Golden Rock Coin Pot/Pot", "@Potsanity - Roots of Yggdrasil (3)/Golden Rock Coin Pot"}, -- [ROY E-6] Golden Rock Coin Pot
    [430431] = {"@Annwfn/Fairy Watchtower Item Pot/Pot", "@Potsanity - Annwfn (1)/Fairy Watchtower Item Pot"}, -- [ANN C-2] Fairy Watchtower Item Pot
    [430432] = {"@Annwfn/Pre-Kaliya Hidden Coin Pot/Pot", "@Potsanity - Annwfn (1)/Pre-Kaliya Hidden Coin Pot"}, -- [ANN D-2] Pre-Kaliya Hidden Coin Pot
    [430433] = {"@Annwfn/Kaliya's Item Pot/Pot", "@Potsanity - Annwfn (1)/Kaliya's Item Pot"}, -- [ANN D-1] Kaliya's Item Pot
    [430434] = {"@Annwfn/Kukulkan's Grail Coin Pot/Pot", "@Potsanity - Annwfn (1)/Kukulkan's Grail Coin Pot"}, -- [ANN C-3] Kukulkan's Grail Coin Pot
    [430435] = {"@Annwfn/Kukulkan's Grail Weight Pot/Pot", "@Potsanity - Annwfn (1)/Kukulkan's Grail Weight Pot"}, -- [ANN C-3] Kukulkan's Grail Weight Pot
    [430436] = {"@Annwfn/Fairy King's Coin Pot/Pot", "@Potsanity - Annwfn (2)/Fairy King's Coin Pot"}, -- [ANN B-2] Fairy King's Coin Pot
    [430437] = {"@Annwfn/Center Item Pot #1/Pot", "@Potsanity - Annwfn (2)/Center Item Pot #1"}, -- [ANN D-3] Center Item Pot #1
    [430438] = {"@Annwfn/Center Item Pot #2/Pot", "@Potsanity - Annwfn (2)/Center Item Pot #2"}, -- [ANN D-3] Center Item Pot #2
    [430439] = {"@Annwfn/Huracan's Item Pot/Pot", "@Potsanity - Annwfn (2)/Huracan's Item Pot"}, -- [ANN E-3] Huracan's Item Pot
    [430440] = {"@Annwfn/Mantra Watchtower Weight Pot/Pot", "@Potsanity - Annwfn (2)/Mantra Watchtower Weight Pot"}, -- [ANN E-2] Mantra Watchtower Weight Pot
    [430441] = {"@Annwfn/Look Away Weight Pot/Pot", "@Potsanity - Annwfn (3)/Look Away Weight Pot"}, -- [ANN C-4] Look Away Weight Pot
    [430442] = {"@Annwfn/Bifrost Left Weight Pot/Pot", "@Potsanity - Annwfn (3)/Bifrost Left Weight Pot"}, -- [ANN B-5] Bifrost Left Weight Pot
    [430443] = {"@Annwfn/Bifrost Right Item Pot/Pot", "@Potsanity - Annwfn (3)/Bifrost Right Item Pot"}, -- [ANN D-5] Bifrost Right Item Pot
    [430444] = {"@Annwfn/Bifrost Right Coin Pot/Pot", "@Potsanity - Annwfn (3)/Bifrost Right Coin Pot"}, -- [ANN D-5] Bifrost Right Coin Pot
    [430445] = {"@Annwfn/Feathercross One-Way Pot/Pot", "@Potsanity - Annwfn (3)/Feathercross One-Way Pot"}, -- [ANN E-5] Feathercross One-Way Pot
    [430446] = {"@Annwfn/Ixtab Coin Pot/Pot", "@Potsanity - Annwfn (4)/Ixtab Coin Pot"}, -- [ANN D-4] Ixtab Coin Pot
    [430447] = {"@Annwfn/Death's Prison Hidden Coin Pot/Pot", "@Potsanity - Annwfn (4)/Death's Prison Hidden Coin Pot"}, -- [ANN G-4] Death's Prison Hidden Coin Pot
    [430448] = {"@Annwfn/Pre-Kujata Weight Pot/Pot", "@Potsanity - Annwfn (4)/Pre-Kujata Weight Pot"}, -- [ANN F-3] Pre-Kujata Weight Pot
    [430449] = {"@Immortal Battlefield/Left Altar Lower Item Pot/Pot", "@Potsanity - Immortal Battlefield (2)/Left Altar Lower Item Pot"}, -- [IB D-3] Left Altar Lower Item Pot
    [430450] = {"@Immortal Battlefield/Above Frontside Grail Coin Pot/Pot", "@Potsanity - Immortal Battlefield (3)/Above Frontside Grail Coin Pot"}, -- [IB G-2] Above Frontside Grail Coin Pot
    [430451] = {"@Immortal Battlefield/Frontside Grail Upper Coin Pot/Pot", "@Potsanity - Immortal Battlefield (4)/Frontside Grail Upper Coin Pot"}, -- [IB G-3] Frontside Grail Upper Coin Pot
    [430452] = {"@Immortal Battlefield/Right of Spiral Boat Coin Pot/Pot", "@Potsanity - Immortal Battlefield (3)/Right of Spiral Boat Coin Pot"}, -- [IB F-4] Right of Spiral Boat Coin Pot
    [430453] = {"@Immortal Battlefield/Path to Time Altar Coin Pot/Pot", "@Potsanity - Immortal Battlefield (6)/Path to Time Altar Coin Pot"}, -- [IB B-5] Path to Time Altar Coin Pot
    [430454] = {"@Immortal Battlefield/Above Backside Grail Coin Pot/Pot", "@Potsanity - Immortal Battlefield (2)/Above Backside Grail Coin Pot"}, -- [IB D-5] Above Backside Grail Coin Pot
    [430455] = {"@Immortal Battlefield/Corona Arsenal Right Item Pot/Pot", "@Potsanity - Immortal Battlefield (5)/Corona Arsenal Right Item Pot"}, -- [IB I-6] Corona Arsenal Right Item Pot
    [430456] = {"@Immortal Battlefield/Path of Destruction Dropdown Coin Pot/Pot", "@Potsanity - Immortal Battlefield (4)/Path of Destruction Dropdown Coin Pot"}, -- [IB H-5] Path of Destruction Dropdown Coin Pot
    [430457] = {"@Immortal Battlefield/Inferno Corridor Coin Pot/Pot", "@Potsanity - Immortal Battlefield (7)/Inferno Corridor Coin Pot"}, -- [IB D-7] Inferno Corridor Coin Pot
    [430458] = {"@Immortal Battlefield/Submerged Sigil Weight Pot/Pot", "@Potsanity - Immortal Battlefield (3)/Submerged Sigil Weight Pot"}, -- [IB F-6] Submerged Sigil Weight Pot
    [430459] = {"@Immortal Battlefield/Left of Lava Weapon Vault Weight Pot/Pot", "@Potsanity - Immortal Battlefield (5)/Left of Lava Weapon Vault Weight Pot"}, -- [IB B-6] Left of Lava Weapon Vault Weight Pot
    [430460] = {"@Immortal Battlefield/Left Soul Gate Weight Pot/Pot", "@Potsanity - Immortal Battlefield (6)/Left Soul Gate Weight Pot"}, -- [IB B-7] Left Soul Gate Weight Pot
    [430461] = {"@Immortal Battlefield/Inferno Corridor Weight Pot/Pot", "@Potsanity - Immortal Battlefield (5)/Inferno Corridor Weight Pot"}, -- [IB C-7] Inferno Corridor Weight Pot
    [430462] = {"@Immortal Battlefield/Cetus Item Pot/Pot", "@Potsanity - Immortal Battlefield (1)/Cetus Item Pot"}, -- [IB E-1] Cetus Item Pot
    [430463] = {"@Immortal Battlefield/Top-Left Weapon Vault Item Pot/Pot", "@Potsanity - Immortal Battlefield (1)/Top-Left Weapon Vault Item Pot"}, -- [IB C-1] Top-Left Weapon Vault Item Pot
    [430464] = {"@Immortal Battlefield/Before Fake Wall Puzzle Item Pot/Pot", "@Potsanity - Immortal Battlefield (1)/Before Fake Wall Puzzle Item Pot"}, -- [IB C-2] Before Fake Wall Puzzle Item Pot
    [430465] = {"@Immortal Battlefield/Corridor of Wind Item Pot/Pot", "@Potsanity - Immortal Battlefield (1)/Corridor of Wind Item Pot"}, -- [IB D-2] Corridor of Wind Item Pot
    [430466] = {"@Immortal Battlefield/Below Hidden Sigil Item Pot/Pot", "@Potsanity - Immortal Battlefield (4)/Below Hidden Sigil Item Pot"}, -- [IB G-5] Below Hidden Sigil Item Pot
    [430467] = {"@Immortal Battlefield/Path to Time Altar Item Pot/Pot", "@Potsanity - Immortal Battlefield (6)/Path to Time Altar Item Pot"}, -- [IB B-5] Path to Time Altar Item Pot
    [430468] = {"@Immortal Battlefield/Frontside Grail Lower Item Pot/Pot", "@Potsanity - Immortal Battlefield (4)/Frontside Grail Lower Item Pot"}, -- [IB G-3] Frontside Grail Lower Item Pot
    [430469] = {"@Immortal Battlefield/Jormungandr Mural Item Pot/Pot", "@Potsanity - Immortal Battlefield (2)/Jormungandr Mural Item Pot"}, -- [IB E-6] Jormungandr Mural Item Pot
    [430470] = {"@Immortal Battlefield/Map Chest Right Item Pot/Pot", "@Potsanity - Immortal Battlefield (3)/Map Chest Right Item Pot"}, -- [IB F-2] Map Chest Right Item Pot
    [430471] = {"@Immortal Battlefield/Alviss Item Pot/Pot", "@Potsanity - Immortal Battlefield (7)/Alviss Item Pot"}, -- [IB G-7] Alviss Item Pot
    [430472] = {"@Immortal Battlefield/Under Fake Wall Puzzle Item Pot/Pot", "@Potsanity - Immortal Battlefield (1)/Under Fake Wall Puzzle Item Pot"}, -- [IB B-2] Under Fake Wall Puzzle Item Pot
    [430473] = {"@Immortal Battlefield/Map Chest Left Item Pot/Pot", "@Potsanity - Immortal Battlefield (3)/Map Chest Left Item Pot"}, -- [IB F-2] Map Chest Left Item Pot
    [430474] = {"@Immortal Battlefield/Path to Destruction Item Pot/Pot", "@Potsanity - Immortal Battlefield (5)/Path to Destruction Item Pot"}, -- [IB H-5] Path to Destruction Item Pot
    [430475] = {"@Immortal Battlefield/Right of Hiro Roderick Item Pot/Pot", "@Potsanity - Immortal Battlefield (4)/Right of Hiro Roderick Item Pot"}, -- [IB G-6] Right of Hiro Roderick Item Pot
    [430476] = {"@Immortal Battlefield/Moon Altar Item Pot/Pot", "@Potsanity - Immortal Battlefield (7)/Moon Altar Item Pot"}, -- [IB E-7] Moon Altar Item Pot
    [430478] = {"@Immortal Battlefield/Time Altar Item Pot/Pot", "@Potsanity - Immortal Battlefield (6)/Time Altar Item Pot"}, -- [IB B-4] Time Altar Item Pot
    [430479] = {"@Immortal Battlefield/Left Altar Upper Item Pot/Pot", "@Potsanity - Immortal Battlefield (2)/Left Altar Upper Item Pot"}, -- [IB D-3] Left Altar Upper Item Pot
    [430480] = {"@Immortal Battlefield/Moon Altar Coin Pot/Pot", "@Potsanity - Immortal Battlefield (7)/Moon Altar Coin Pot"}, -- [IB E-7] Moon Altar Coin Pot
    [430481] = {"@Immortal Battlefield/Left of Spiral Boat Coin Pot/Pot", "@Potsanity - Immortal Battlefield (2)/Left of Spiral Boat Coin Pot"}, -- [IB D-4] Left of Spiral Boat Coin Pot
    [430482] = {"@Immortal Battlefield/Path to Time Altar Hidden Coin Pot/Pot", "@Potsanity - Immortal Battlefield (6)/Path to Time Altar Hidden Coin Pot"}, -- [IB B-5] Path to Time Altar Hidden Coin Pot
    [430483] = {"@Icefire Treetop/BTK Coin Pot/Pot", "@Potsanity - Icefire Treetop (2)/BTK Coin Pot"}, -- [IT A-1] BTK Coin Pot
    [430484] = {"@Icefire Treetop/Ratatoskr Surprise Item Pot/Pot", "@Potsanity - Icefire Treetop (4)/Ratatoskr Surprise Item Pot"}, -- [IT C-1] Ratatoskr Surprise Item Pot
    [430485] = {"@Icefire Treetop/Altar of Life Item Pot/Pot", "@Potsanity - Icefire Treetop (3)/Altar of Life Item Pot"}, -- [IT A-2] Altar of Life Item Pot
    [430486] = {"@Icefire Treetop/Fireside Elevator Coin Pot/Pot", "@Potsanity - Icefire Treetop (3)/Fireside Elevator Coin Pot"}, -- [IT B-2] Fireside Elevator Coin Pot
    [430487] = {"@Icefire Treetop/Altar of Life Approach Coin Pot/Pot", "@Potsanity - Icefire Treetop (3)/Altar of Life Approach Coin Pot"}, -- [IT A-3] Altar of Life Approach Coin Pot
    [430488] = {"@Icefire Treetop/Below Frontside Grail Coin Pot/Pot", "@Potsanity - Icefire Treetop (2)/Below Frontside Grail Coin Pot"}, -- [IT B-3] Below Frontside Grail Coin Pot
    [430489] = {"@Icefire Treetop/Surtr's Antechamber Item Pot/Pot", "@Potsanity - Icefire Treetop (2)/Surtr's Antechamber Item Pot"}, -- [IT C-3] Surtr's Antechamber Item Pot
    [430490] = {"@Icefire Treetop/Vedfolnir Left Item Pot/Pot", "@Potsanity - Icefire Treetop (3)/Vedfolnir Left Item Pot"}, -- [IT B-4] Vedfolnir Left Item Pot
    [430491] = {"@Icefire Treetop/Vedfolnir Right Item Pot/Pot", "@Potsanity - Icefire Treetop (3)/Vedfolnir Right Item Pot"}, -- [IT B-4] Vedfolnir Right Item Pot
    [430492] = {"@Icefire Treetop/Mino Top Right Coin Pot/Pot", "@Potsanity - Icefire Treetop (1)/Mino Top Right Coin Pot"}, -- [IT C-4] Mino Top Right Coin Pot
    [430493] = {"@Icefire Treetop/Mino Center Item Pot/Pot", "@Potsanity - Icefire Treetop (1)/Mino Center Item Pot"}, -- [IT C-4] Mino Center Item Pot
    [430494] = {"@Icefire Treetop/Mino Bottom Left Coin Pot/Pot", "@Potsanity - Icefire Treetop (1)/Mino Bottom Left Coin Pot"}, -- [IT C-4] Mino Bottom Left Coin Pot
    [430495] = {"@Icefire Treetop/Mino Bottom Right Weight Pot/Pot", "@Potsanity - Icefire Treetop (1)/Mino Bottom Right Weight Pot"}, -- [IT C-4] Mino Bottom Right Weight Pot
    [430496] = {"@Icefire Treetop/Bombable Wall Coin Pot/Pot", "@Potsanity - Icefire Treetop (1)/Bombable Wall Coin Pot"}, -- [IT C-5] Bombable Wall Coin Pot
    [430497] = {"@Icefire Treetop/Above Vidofnir Item Pot/Pot", "@Potsanity - Icefire Treetop (2)/Above Vidofnir Item Pot"}, -- [IT D-5] Above Vidofnir Item Pot
    [430498] = {"@Icefire Treetop/Lower Statue Item Pot/Pot", "@Potsanity - Icefire Treetop (4)/Lower Statue Item Pot"}, -- [IT E-1] Lower Statue Item Pot
    [430499] = {"@Icefire Treetop/Left Ladder Coin Pot/Pot", "@Potsanity - Icefire Treetop (5)/Left Ladder Coin Pot"}, -- [IT F-1] Left Ladder Coin Pot
    [430500] = {"@Icefire Treetop/Backside Grail Hidden Coin Pot #1/Pot", "@Potsanity - Icefire Treetop (4)/Backside Grail Hidden Coin Pot #1"}, -- [IT F-1] Backside Grail Hidden Coin Pot #1
    [430501] = {"@Icefire Treetop/Backside Grail Hidden Coin Pot #2/Pot", "@Potsanity - Icefire Treetop (5)/Backside Grail Hidden Coin Pot #2"}, -- [IT G-1] Backside Grail Hidden Coin Pot #2
    [430502] = {"@Icefire Treetop/Backside Grail Hidden Item Pot/Pot", "@Potsanity - Icefire Treetop (5)/Backside Grail Hidden Item Pot"}, -- [IT G-1] Backside Grail Hidden Item Pot
    [430503] = {"@Icefire Treetop/Great Bird Nest Item Pot/Pot", "@Potsanity - Icefire Treetop (4)/Great Bird Nest Item Pot"}, -- [IT E-2] Great Bird Nest Item Pot
    [430504] = {"@Icefire Treetop/Niflheim Stalactites Item Pot/Pot", "@Potsanity - Icefire Treetop (4)/Niflheim Stalactites Item Pot"}, -- [IT E-3] Niflheim Stalactites Item Pot
    [430505] = {"@Icefire Treetop/Iceside Elevator Item Pot/Pot", "@Potsanity - Icefire Treetop (5)/Iceside Elevator Item Pot"}, -- [IT F-3] Iceside Elevator Item Pot
    [430506] = {"@Icefire Treetop/Skull in Background Upper Coin Pot/Pot", "@Potsanity - Icefire Treetop (2)/Skull in Background Upper Coin Pot"}, -- [IT E-4] Skull in Background Upper Coin Pot
    [430507] = {"@Divine Fortress/Moving Block Upper Coin Pot/Pot", "@Potsanity - Divine Fortress (3)/Moving Block Upper Coin Pot"}, -- [DF B-2] Moving Block Upper Coin Pot
    [430508] = {"@Divine Fortress/Breakable Push Block Coin Pot/Pot", "@Potsanity - Divine Fortress (4)/Breakable Push Block Coin Pot"}, -- [DF C-2] Breakable Push Block Coin Pot
    [430509] = {"@Divine Fortress/Yuga Wheel Item Pot/Pot", "@Potsanity - Divine Fortress (4)/Yuga Wheel Item Pot"}, -- [DF D-2] Yuga Wheel Item Pot
    [430510] = {"@Divine Fortress/Dwarves' Hideout Right Pot #1/Pot", "@Potsanity - Divine Fortress (2)/Dwarves' Hideout Right Pot #1"}, -- [DF A-3] Dwarves' Hideout Right Pot #1
    [430511] = {"@Divine Fortress/Dwarves' Hideout Right Pot #2/Pot", "@Potsanity - Divine Fortress (1)/Dwarves' Hideout Right Pot #2"}, -- [DF A-3] Dwarves' Hideout Right Pot #2
    [430512] = {"@Divine Fortress/Footprint Coin Pot/Pot", "@Potsanity - Divine Fortress (3)/Footprint Coin Pot"}, -- [DF C-3] Footprint Coin Pot
    [430513] = {"@Divine Fortress/Moving Block Lower Item Pot/Pot", "@Potsanity - Divine Fortress (2)/Moving Block Lower Item Pot"}, -- [DF B-2] Moving Block Lower Item Pot
    [430514] = {"@Divine Fortress/Corridor to Gate Item Pot/Pot", "@Potsanity - Divine Fortress (2)/Corridor to Gate Item Pot"}, -- [DF A-4] Corridor to Gate Item Pot
    [430515] = {"@Divine Fortress/Antechamber - Ladder Weight Pot/Pot", "@Potsanity - Divine Fortress (3)/Antechamber - Ladder Weight Pot"}, -- [DF B-4] Antechamber - Ladder Weight Pot
    [430516] = {"@Divine Fortress/Antechamber - Gullinbursti Item Pot/Pot", "@Potsanity - Divine Fortress (2)/Antechamber - Gullinbursti Item Pot"}, -- [DF B-4] Antechamber - Gullinbursti Item Pot
    [430517] = {"@Divine Fortress/Antechamber - Ledge Coin Pot/Pot", "@Potsanity - Divine Fortress (2)/Antechamber - Ledge Coin Pot"}, -- [DF B-4] Antechamber - Ledge Coin Pot
    [430518] = {"@Divine Fortress/Above Mantra Mural Coin Pot/Pot", "@Potsanity - Divine Fortress (1)/Above Mantra Mural Coin Pot"}, -- [DF D-4] Above Mantra Mural Coin Pot
    [430519] = {"@Divine Fortress/Pre-Hugin and Munin Weight Pot/Pot", "@Potsanity - Divine Fortress (1)/Pre-Hugin and Munin Weight Pot"}, -- [DF E-4] Pre-Hugin and Munin Weight Pot
    [430520] = {"@Divine Fortress/Shuhoka Upper Item Pot/Pot", "@Potsanity - Divine Fortress (3)/Shuhoka Upper Item Pot"}, -- [DF B-5] Shuhoka Upper Item Pot
    [430521] = {"@Divine Fortress/Shuhoka Lower Weight Pot/Pot", "@Potsanity - Divine Fortress (3)/Shuhoka Lower Weight Pot"}, -- [DF B-5] Shuhoka Lower Weight Pot
    [430522] = {"@Divine Fortress/Frey's Ship Coin Pot/Pot", "@Potsanity - Divine Fortress (1)/Frey's Ship Coin Pot"}, -- [DF D-3] Frey's Ship Coin Pot
    [430523] = {"@Divine Fortress/Divine Soul Gate Item Pot/Pot", "@Potsanity - Divine Fortress (1)/Divine Soul Gate Item Pot"}, -- [DF C-5] Divine Soul Gate Item Pot
    [430524] = {"@Shrine of the Frost Giants/Mimics Right Item Pot/Pot", "@Potsanity - Shrine of the Frost Giants (4)/Mimics Right Item Pot"}, -- [SFG C-2] Mimics Right Item Pot
    [430525] = {"@Shrine of the Frost Giants/Mimics Left Item Pot/Pot", "@Potsanity - Shrine of the Frost Giants (4)/Mimics Left Item Pot"}, -- [SFG C-2] Mimics Left Item Pot
    [430526] = {"@Shrine of the Frost Giants/Mantra Mural Exit Item Pot/Pot", "@Potsanity - Shrine of the Frost Giants (1)/Mantra Mural Exit Item Pot"}, -- [SFG C-3] Mantra Mural Exit Item Pot
    [430527] = {"@Shrine of the Frost Giants/Golden Altar Coin Pot/Pot", "@Potsanity - Shrine of the Frost Giants (1)/Golden Altar Coin Pot"}, -- [SFG E-3] Golden Altar Coin Pot
    [430528] = {"@Shrine of the Frost Giants/Bergelmir Blocking Item Pot/Pot", "@Potsanity - Shrine of the Frost Giants (3)/Bergelmir Blocking Item Pot"}, -- [SFG A-4] Bergelmir Blocking Item Pot
    [430529] = {"@Shrine of the Frost Giants/Weapon Fairy - Lower Weight Pot/Pot", "@Potsanity - Shrine of the Frost Giants (1)/Weapon Fairy - Lower Weight Pot"}, -- [SFG C-4] Weapon Fairy - Lower Weight Pot
    [430530] = {"@Shrine of the Frost Giants/Weapon Fairy - Upper Coin Pot/Pot", "@Potsanity - Shrine of the Frost Giants (1)/Weapon Fairy - Upper Coin Pot"}, -- [SFG C-4] Weapon Fairy - Upper Coin Pot
    [430531] = {"@Shrine of the Frost Giants/Path of Snow Weight Pot/Pot", "@Potsanity - Shrine of the Frost Giants (2)/Path of Snow Weight Pot"}, -- [SFG E-4] Path of Snow Weight Pot
    [430532] = {"@Shrine of the Frost Giants/Path of Snow Coin Pot/Pot", "@Potsanity - Shrine of the Frost Giants (2)/Path of Snow Coin Pot"}, -- [SFG E-4] Path of Snow Coin Pot
    [430533] = {"@Shrine of the Frost Giants/Weapon Vault Item Pot/Pot", "@Potsanity - Shrine of the Frost Giants (2)/Weapon Vault Item Pot"}, -- [SFG B-5] Weapon Vault Item Pot
    [430534] = {"@Shrine of the Frost Giants/Grail Coin Pot/Pot", "@Potsanity - Shrine of the Frost Giants (3)/Grail Coin Pot"}, -- [SFG C-5] Grail Coin Pot
    [430535] = {"@Shrine of the Frost Giants/Titanomachy Monument Item Pot/Pot", "@Potsanity - Shrine of the Frost Giants (1)/Titanomachy Monument Item Pot"}, -- [SFG D-5] Titanomachy Monument Item Pot
    [430536] = {"@Shrine of the Frost Giants/Footprint Weight Pot/Pot", "@Potsanity - Shrine of the Frost Giants (2)/Footprint Weight Pot"}, -- [SFG E-5] Footprint Weight Pot
    [430537] = {"@Shrine of the Frost Giants/Footprint Coin Pot/Pot", "@Potsanity - Shrine of the Frost Giants (2)/Footprint Coin Pot"}, -- [SFG E-5] Footprint Coin Pot
    [430538] = {"@Shrine of the Frost Giants/Sacred Wine Corridor Coin Pot/Pot", "@Potsanity - Shrine of the Frost Giants (3)/Sacred Wine Corridor Coin Pot"}, -- [SFG C-6] Sacred Wine Corridor Coin Pot
    [430540] = {"@Shrine of the Frost Giants/Right Snow Drop Coin Pot/Pot", "@Potsanity - Shrine of the Frost Giants (3)/Right Snow Drop Coin Pot"}, -- [SFG D-6] Right Snow Drop Coin Pot
    [430541] = {"@Shrine of the Frost Giants/Altar of Birth Approach Item Pot/Pot", "@Potsanity - Shrine of the Frost Giants (3)/Altar of Birth Approach Item Pot"}, -- [SFG D-7] Altar of Birth Approach Item Pot
    [430543] = {"@Shrine of the Frost Giants/Tezcatlipoca Reward Item Pot/Pot", "@Potsanity - Shrine of the Frost Giants (5)/Tezcatlipoca Reward Item Pot"}, -- [SFGB A-1] Tezcatlipoca Reward Item Pot
    [430544] = {"@Shrine of the Frost Giants/Corridor of Blood Left Coin Pot/Pot", "@Potsanity - Shrine of the Frost Giants (4)/Corridor of Blood Left Coin Pot"}, -- [SFGB C-1] Corridor of Blood Left Coin Pot
    [430545] = {"@Shrine of the Frost Giants/Corridor of Blood Right Weight Pot/Pot", "@Potsanity - Shrine of the Frost Giants (4)/Corridor of Blood Right Weight Pot"}, -- [SFGB C-1] Corridor of Blood Right Weight Pot
    [430546] = {"@Shrine of the Frost Giants/Left Snow Drop Coin Pot/Pot", "@Potsanity - Shrine of the Frost Giants (4)/Left Snow Drop Coin Pot"}, -- [SFG A-4] Left Snow Drop Coin Pot
    [430547] = {"@Gate of the Dead/Unicorn Reward Coin Pot/Pot", "@Potsanity - Gate of the Dead (2)/Unicorn Reward Coin Pot"}, -- [GOTD C-1] Unicorn Reward Coin Pot
    [430548] = {"@Gate of the Dead/Pre-Unicorn Weight Pot/Pot", "@Potsanity - Gate of the Dead (2)/Pre-Unicorn Weight Pot"}, -- [GOTD C-2] Pre-Unicorn Weight Pot
    [430549] = {"@Gate of the Dead/Pre-Unicorn Item Pot/Pot", "@Potsanity - Gate of the Dead (2)/Pre-Unicorn Item Pot"}, -- [GOTD C-2] Pre-Unicorn Item Pot
    [430550] = {"@Gate of the Dead/Aytum's Coin Pot/Pot", "@Potsanity - Gate of the Dead (1)/Aytum's Coin Pot"}, -- [GOTD B-3] Aytum's Coin Pot
    [430551] = {"@Gate of the Dead/Below Grail Item Pot/Pot", "@Potsanity - Gate of the Dead (3)/Below Grail Item Pot"}, -- [GOTD D-3] Below Grail Item Pot
    [430552] = {"@Gate of the Dead/Flipped Push Block Item Pot/Pot", "@Potsanity - Gate of the Dead (3)/Flipped Push Block Item Pot"}, -- [GOTD E-3] Flipped Push Block Item Pot
    [430553] = {"@Gate of the Dead/Death Trap Item Pot/Pot", "@Potsanity - Gate of the Dead (1)/Death Trap Item Pot"}, -- [GOTD B-4] Death Trap Item Pot
    [430554] = {"@Gate of the Dead/Soul Gate Coin Pot/Pot", "@Potsanity - Gate of the Dead (2)/Soul Gate Coin Pot"}, -- [GOTD C-4] Soul Gate Coin Pot
    [430555] = {"@Gate of the Dead/Thoth's Upper Coin Chest/Pot", "@Potsanity - Gate of the Dead (1)/Thoth's Upper Coin Chest"}, -- [GOTD B-5] Thoth's Upper Coin Chest
    [430556] = {"@Gate of the Dead/Thoth's Lower Item Chest/Pot", "@Potsanity - Gate of the Dead (1)/Thoth's Lower Item Chest"}, -- [GOTD B-5] Thoth's Lower Item Chest
    [430557] = {"@Gate of the Dead/Pillar Pepper Puzzle Item Pot/Pot", "@Potsanity - Gate of the Dead (3)/Pillar Pepper Puzzle Item Pot"}, -- [GOTD D-5] Pillar Pepper Puzzle Item Pot
    [430558] = {"@Gate of the Dead/Horus Item Pot/Pot", "@Potsanity - Gate of the Dead (4)/Horus Item Pot"}, -- [GOTD E-5] Horus Item Pot
    [430559] = {"@Gate of the Dead/Wedjet Gate Solo Item Pot #1/Pot", "@Potsanity - Gate of the Dead (4)/Wedjet Gate Solo Item Pot #1"}, -- [GOTD F-5] Wedjet Gate Solo Item Pot #1
    [430560] = {"@Gate of the Dead/Wedjet Gate Solo Item Pot #2/Pot", "@Potsanity - Gate of the Dead (4)/Wedjet Gate Solo Item Pot #2"}, -- [GOTD F-5] Wedjet Gate Solo Item Pot #2
    [430561] = {"@Gate of the Dead/Dwarves' Puzzle Item Pot/Pot", "@Potsanity - Gate of the Dead (1)/Dwarves' Puzzle Item Pot"}, -- [GOTD B-6] Dwarves' Puzzle Item Pot
    [430562] = {"@Gate of the Dead/Room of the Dark Night Item Pot/Pot", "@Potsanity - Gate of the Dead (3)/Room of the Dark Night Item Pot"}, -- [GOTD D-6] Room of the Dark Night Item Pot
    [430563] = {"@Gate of the Dead/Laser Beams Item Pot/Pot", "@Potsanity - Gate of the Dead (2)/Laser Beams Item Pot"}, -- [GOTD C-7] Laser Beams Item Pot
    [430564] = {"@Gate of the Dead/Laser Beams Coin Pot/Pot", "@Potsanity - Gate of the Dead (3)/Laser Beams Coin Pot"}, -- [GOTD C-7] Laser Beams Coin Pot
    [430565] = {"@Takamagahara Shrine/Maze Top-Left Item Pot/Pot", "@Potsanity - Takamagahara Shrine (2)/Maze Top-Left Item Pot"}, -- [TS B-4] Maze Top-Left Item Pot
    [430566] = {"@Takamagahara Shrine/Pre-Belial Coin Pot/Pot", "@Potsanity - Takamagahara Shrine (5)/Pre-Belial Coin Pot"}, -- [TS A-1] Pre-Belial Coin Pot
    [430567] = {"@Takamagahara Shrine/Yuga Wheel Item Pot/Pot", "@Potsanity - Takamagahara Shrine (5)/Yuga Wheel Item Pot"}, -- [TS B-1] Yuga Wheel Item Pot
    [430568] = {"@Takamagahara Shrine/Above Grail Item Pot/Pot", "@Potsanity - Takamagahara Shrine (3)/Above Grail Item Pot"}, -- [TS C-2] Above Grail Item Pot
    [430569] = {"@Takamagahara Shrine/Next to Chest Coin Pot/Pot", "@Potsanity - Takamagahara Shrine (1)/Next to Chest Coin Pot"}, -- [TS D-2] Next to Chest Coin Pot
    [430570] = {"@Takamagahara Shrine/Spirit Palace Hidden Coin Pot/Pot", "@Potsanity - Takamagahara Shrine (3)/Spirit Palace Hidden Coin Pot"}, -- [TS C-3] Spirit Palace Hidden Coin Pot
    [430571] = {"@Takamagahara Shrine/Spirit Palace Right Item Pot/Pot", "@Potsanity - Takamagahara Shrine (3)/Spirit Palace Right Item Pot"}, -- [TS C-3] Spirit Palace Right Item Pot
    [430572] = {"@Takamagahara Shrine/Amenominakanushi Top-Left Coin Pot/Pot", "@Potsanity - Takamagahara Shrine (1)/Amenominakanushi Top-Left Coin Pot"}, -- [TS D-3] Amenominakanushi Top-Left Coin Pot
    [430573] = {"@Takamagahara Shrine/Raijin and Fujin Reward Item Pot/Pot", "@Potsanity - Takamagahara Shrine (2)/Raijin and Fujin Reward Item Pot"}, -- [TS F-3] Raijin and Fujin Reward Item Pot
    [430574] = {"@Takamagahara Shrine/Maze Middle Coin Pot/Pot", "@Potsanity - Takamagahara Shrine (3)/Maze Middle Coin Pot"}, -- [TS B-4] Maze Middle Coin Pot
    [430575] = {"@Takamagahara Shrine/Maze Bottom-Left Item Pot/Pot", "@Potsanity - Takamagahara Shrine (3)/Maze Bottom-Left Item Pot"}, -- [TS B-4] Maze Bottom-Left Item Pot
    [430576] = {"@Takamagahara Shrine/Left Dragon Path Weight Pot/Pot", "@Potsanity - Takamagahara Shrine (4)/Left Dragon Path Weight Pot"}, -- [TS C-4] Left Dragon Path Weight Pot
    [430577] = {"@Takamagahara Shrine/Amenominakanushi Pre-Ladder Coin Pot/Pot", "@Potsanity - Takamagahara Shrine (2)/Amenominakanushi Pre-Ladder Coin Pot"}, -- [TS D-4] Amenominakanushi Pre-Ladder Coin Pot
    [430578] = {"@Takamagahara Shrine/Amenominakanushi Bottom Level Item Pot/Pot", "@Potsanity - Takamagahara Shrine (1)/Amenominakanushi Bottom Level Item Pot"}, -- [TS D-4] Amenominakanushi Bottom Level Item Pot
    [430579] = {"@Takamagahara Shrine/Spinning Platforms Left Item Pot/Pot", "@Potsanity - Takamagahara Shrine (1)/Spinning Platforms Left Item Pot"}, -- [TS C-5] Spinning Platforms Left Item Pot
    [430580] = {"@Takamagahara Shrine/Spinning Platforms Right Weight Pot /Pot", "@Potsanity - Takamagahara Shrine (1)/Spinning Platforms Right Weight Pot "}, -- [TS C-5] Spinning Platforms Right Weight Pot 
    [430581] = {"@Takamagahara Shrine/Falling Platform Weight Pot/Pot", "@Potsanity - Takamagahara Shrine (2)/Falling Platform Weight Pot"}, -- [TS D-5] Falling Platform Weight Pot
    [430582] = {"@Takamagahara Shrine/Falling Platform Item Pot/Pot", "@Potsanity - Takamagahara Shrine (2)/Falling Platform Item Pot"}, -- [TS D-5] Falling Platform Item Pot
    [430583] = {"@Takamagahara Shrine/Breakable Pillar Coin Pot/Pot", "@Potsanity - Takamagahara Shrine (4)/Breakable Pillar Coin Pot"}, -- [TS D-6] Breakable Pillar Coin Pot
    [430584] = {"@Takamagahara Shrine/Amanoiwato Gate Item Pot/Pot", "@Potsanity - Takamagahara Shrine (4)/Amanoiwato Gate Item Pot"}, -- [TS C-7] Amanoiwato Gate Item Pot
    [430585] = {"@Takamagahara Shrine/Stacked Item Pot/Pot", "@Potsanity - Takamagahara Shrine (4)/Stacked Item Pot"}, -- [TS D-7] Stacked Item Pot
    [430586] = {"@Takamagahara Shrine/Upper Corridor Coin Pot/Pot", "@Potsanity - Takamagahara Shrine (4)/Upper Corridor Coin Pot"}, -- [TS D-7] Upper Corridor Coin Pot
    [430587] = {"@Heavens Labyrinth/Ladder from B-2 Mural Item Pot/Pot", "@Potsanity - Heavens Labyrinth (1)/Ladder from B-2 Mural Item Pot"}, -- [HL B-1] Ladder from B-2 Mural Item Pot
    [430588] = {"@Heavens Labyrinth/Weapon Vault Coin Pot/Pot", "@Potsanity - Heavens Labyrinth (3)/Weapon Vault Coin Pot"}, -- [HL B-1] Weapon Vault Coin Pot
    [430589] = {"@Heavens Labyrinth/After Megarock Item Pot/Pot", "@Potsanity - Heavens Labyrinth (1)/After Megarock Item Pot"}, -- [HL A-2] After Megarock Item Pot
    [430590] = {"@Heavens Labyrinth/Path to Chaos Item Pot/Pot", "@Potsanity - Heavens Labyrinth (3)/Path to Chaos Item Pot"}, -- [HL C-2] Path to Chaos Item Pot
    [430591] = {"@Heavens Labyrinth/Soul Gate Hidden Item Pot/Pot", "@Potsanity - Heavens Labyrinth (2)/Soul Gate Hidden Item Pot"}, -- [HL E-5] Soul Gate Hidden Item Pot
    [430592] = {"@Heavens Labyrinth/Below Megarock Coin Pot/Pot", "@Potsanity - Heavens Labyrinth (1)/Below Megarock Coin Pot"}, -- [HL A-3] Below Megarock Coin Pot
    [430593] = {"@Heavens Labyrinth/Celestial Disk Item Pot/Pot", "@Potsanity - Heavens Labyrinth (1)/Celestial Disk Item Pot"}, -- [HL C-3] Celestial Disk Item Pot
    [430594] = {"@Heavens Labyrinth/Celestial Disk Coin Pot/Pot", "@Potsanity - Heavens Labyrinth (1)/Celestial Disk Coin Pot"}, -- [HL C-3] Celestial Disk Coin Pot
    [430595] = {"@Heavens Labyrinth/Spiral Mural Coin Pot/Pot", "@Potsanity - Heavens Labyrinth (2)/Spiral Mural Coin Pot"}, -- [HL E-3] Spiral Mural Coin Pot
    [430596] = {"@Heavens Labyrinth/Typhon's Room Item Pot/Pot", "@Potsanity - Heavens Labyrinth (2)/Typhon's Room Item Pot"}, -- [HL C-4] Typhon's Room Item Pot
    [430597] = {"@Heavens Labyrinth/Twin Vessel Weight Pot/Pot", "@Potsanity - Heavens Labyrinth (3)/Twin Vessel Weight Pot"}, -- [HL A-5] Twin Vessel Weight Pot
    [430598] = {"@Heavens Labyrinth/Twin Vessel Item Pot/Pot", "@Potsanity - Heavens Labyrinth (3)/Twin Vessel Item Pot"}, -- [HL A-5] Twin Vessel Item Pot
    [430599] = {"@Heavens Labyrinth/Scylla's Breakable Wall Coin Pot/Pot", "@Potsanity - Heavens Labyrinth (3)/Scylla's Breakable Wall Coin Pot"}, -- [HL B-5] Scylla's Breakable Wall Coin Pot
    [430600] = {"@Heavens Labyrinth/Arachne's Corridor Item Pot/Pot", "@Potsanity - Heavens Labyrinth (2)/Arachne's Corridor Item Pot"}, -- [HL D-5] Arachne's Corridor Item Pot
    [430601] = {"@Heavens Labyrinth/Arachne's Corridor Coin Pot/Pot", "@Potsanity - Heavens Labyrinth (2)/Arachne's Corridor Coin Pot"}, -- [HL D-5] Arachne's Corridor Coin Pot
    [430602] = {"@Valhalla/Above Grail Coin Pot/Pot", "@Potsanity - Valhalla (2)/Above Grail Coin Pot"}, -- [VAL B-3] Above Grail Coin Pot
    [430604] = {"@Valhalla/Near Third Trickster Item Pot/Pot", "@Potsanity - Valhalla (3)/Near Third Trickster Item Pot"}, -- [VAL D-3] Near Third Trickster Item Pot
    [430605] = {"@Valhalla/Below Zipakna Coin Pot/Pot", "@Potsanity - Valhalla (3)/Below Zipakna Coin Pot"}, -- [VAL D-4] Below Zipakna Coin Pot
    [430606] = {"@Valhalla/Near Second Trickster Coin Pot/Pot", "@Potsanity - Valhalla (2)/Near Second Trickster Coin Pot"}, -- [VAL C-2] Near Second Trickster Coin Pot
    [430607] = {"@Valhalla/Near First Trickster Coin Pot/Pot", "@Potsanity - Valhalla (1)/Near First Trickster Coin Pot"}, -- [VAL A-4] Near First Trickster Coin Pot
    [430608] = {"@Valhalla/Below Bargain Duck Coin Pot/Pot", "@Potsanity - Valhalla (3)/Below Bargain Duck Coin Pot"}, -- [VAL D-4] Below Bargain Duck Coin Pot
    [430609] = {"@Valhalla/Soul Gate Coin Pot/Pot", "@Potsanity - Valhalla (3)/Soul Gate Coin Pot"}, -- [VAL E-2] Soul Gate Coin Pot
    [430610] = {"@Valhalla/Left of Grail Weight Pot/Pot", "@Potsanity - Valhalla (1)/Left of Grail Weight Pot"}, -- [VAL A-3] Left of Grail Weight Pot
    [430611] = {"@Valhalla/Near First Trickster Weight Pot/Pot", "@Potsanity - Valhalla (1)/Near First Trickster Weight Pot"}, -- [VAL A-4] Near First Trickster Weight Pot
    [430612] = {"@Valhalla/Above Laser Statue Weight Pot/Pot", "@Potsanity - Valhalla (2)/Above Laser Statue Weight Pot"}, -- [VAL C-4] Above Laser Statue Weight Pot
    [430613] = {"@Valhalla/Warrior's Aqueduct Item Pot/Pot", "@Potsanity - Valhalla (2)/Warrior's Aqueduct Item Pot"}, -- [VAL C-4] Warrior's Aqueduct Item Pot
    [430614] = {"@Valhalla/Entrance Gate Item Pot/Pot", "@Potsanity - Valhalla (1)/Entrance Gate Item Pot"}, -- [VAL A-2] Entrance Gate Item Pot
    [430615] = {"@Valhalla/Near First Trickster Item Pot/Pot", "@Potsanity - Valhalla (1)/Near First Trickster Item Pot"}, -- [VAL A-4] Near First Trickster Item Pot
    [430616] = {"@Valhalla/Corridor above Jalandhara Item Pot/Pot", "@Potsanity - Valhalla (2)/Corridor above Jalandhara Item Pot"}, -- [VAL B-4] Corridor above Jalandhara Item Pot
    [430617] = {"@Dark Star Lords Mausoleum/Left Ladder to Stars Coin Pot/Pot", "@Potsanity - Dark Star Lords Mausoleum (4)/Left Ladder to Stars Coin Pot"}, -- [DSLM C-2] Left Ladder to Stars Coin Pot
    [430618] = {"@Dark Star Lords Mausoleum/Right Ladder to Stars Item Pot/Pot", "@Potsanity - Dark Star Lords Mausoleum (5)/Right Ladder to Stars Item Pot"}, -- [DSLM C-2] Right Ladder to Stars Item Pot
    [430619] = {"@Dark Star Lords Mausoleum/Kero Coin Pot/Pot", "@Potsanity - Dark Star Lords Mausoleum (2)/Kero Coin Pot"}, -- [DSLM C-2] Kero Coin Pot
    [430620] = {"@Dark Star Lords Mausoleum/Use Crystal Skull Item Pot/Pot", "@Potsanity - Dark Star Lords Mausoleum (5)/Use Crystal Skull Item Pot"}, -- [DSLM B-3] Use Crystal Skull Item Pot
    [430621] = {"@Dark Star Lords Mausoleum/Altar of Atum Item Pot/Pot", "@Potsanity - Dark Star Lords Mausoleum (2)/Altar of Atum Item Pot"}, -- [DSLM C-3] Altar of Atum Item Pot
    [430622] = {"@Dark Star Lords Mausoleum/Ladder to Atum Item Pot #1/Pot", "@Potsanity - Dark Star Lords Mausoleum (2)/Ladder to Atum Item Pot #1"}, -- [DSLM C-4] Ladder to Atum Item Pot #1
    [430623] = {"@Dark Star Lords Mausoleum/Grail Top-Right Item Pot/Pot", "@Potsanity - Dark Star Lords Mausoleum (1)/Grail Top-Right Item Pot"}, -- [DSLM B-4] Grail Top-Right Item Pot
    [430624] = {"@Dark Star Lords Mausoleum/Ladder to Atum Item Pot #2/Pot", "@Potsanity - Dark Star Lords Mausoleum (2)/Ladder to Atum Item Pot #2"}, -- [DSLM C-4] Ladder to Atum Item Pot #2
    [430625] = {"@Dark Star Lords Mausoleum/Right of Pyramid Stacked Coin Pot/Pot", "@Potsanity - Dark Star Lords Mausoleum (4)/Right of Pyramid Stacked Coin Pot"}, -- [DSLM E-4] Right of Pyramid Stacked Coin Pot
    [430626] = {"@Dark Star Lords Mausoleum/Right of Pyramid Stacked Item Pot/Pot", "@Potsanity - Dark Star Lords Mausoleum (4)/Right of Pyramid Stacked Item Pot"}, -- [DSLM E-4] Right of Pyramid Stacked Item Pot
    [430627] = {"@Dark Star Lords Mausoleum/Double Staircases Weight Pot/Pot", "@Potsanity - Dark Star Lords Mausoleum (1)/Double Staircases Weight Pot"}, -- [DSLM B-5] Double Staircases Weight Pot
    [430628] = {"@Dark Star Lords Mausoleum/Ra's Hideout Item Pot/Pot", "@Potsanity - Dark Star Lords Mausoleum (3)/Ra's Hideout Item Pot"}, -- [DSLM C-5] Ra's Hideout Item Pot
    [430629] = {"@Dark Star Lords Mausoleum/Ra's Hideout Coin Pot/Pot", "@Potsanity - Dark Star Lords Mausoleum (3)/Ra's Hideout Coin Pot"}, -- [DSLM C-5] Ra's Hideout Coin Pot
    [430630] = {"@Dark Star Lords Mausoleum/Thunder Antechamber Left Coin Pot/Pot", "@Potsanity - Dark Star Lords Mausoleum (3)/Thunder Antechamber Left Coin Pot"}, -- [DSLM D-5] Thunder Antechamber Left Coin Pot
    [430631] = {"@Dark Star Lords Mausoleum/Thunder Antechamber Right Item Pot/Pot", "@Potsanity - Dark Star Lords Mausoleum (3)/Thunder Antechamber Right Item Pot"}, -- [DSLM D-5] Thunder Antechamber Right Item Pot
    [430632] = {"@Dark Star Lords Mausoleum/Left Winged Statue Item Pot/Pot", "@Potsanity - Dark Star Lords Mausoleum (1)/Left Winged Statue Item Pot"}, -- [DSLM B-6] Left Winged Statue Item Pot
    [430633] = {"@Dark Star Lords Mausoleum/Right Winged Statue Item Pot/Pot", "@Potsanity - Dark Star Lords Mausoleum (3)/Right Winged Statue Item Pot"}, -- [DSLM C-6] Right Winged Statue Item Pot
    [430635] = {"@Dark Star Lords Mausoleum/Room of Judgement Bottom Coin Pot/Pot", "@Potsanity - Dark Star Lords Mausoleum (2)/Room of Judgement Bottom Coin Pot"}, -- [DSLM B-7] Room of Judgement Bottom Coin Pot
    [430636] = {"@Dark Star Lords Mausoleum/Bombable Wall Coin Pot/Pot", "@Potsanity - Dark Star Lords Mausoleum (5)/Bombable Wall Coin Pot"}, -- [DSLM B-3] Bombable Wall Coin Pot
    [430637] = {"@Dark Star Lords Mausoleum/Room of Judgement Left Coin Pot/Pot", "@Potsanity - Dark Star Lords Mausoleum (1)/Room of Judgement Left Coin Pot"}, -- [DSLM B-7] Room of Judgement Left Coin Pot
    [430638] = {"@Dark Star Lords Mausoleum/Room of Judgement Top Item Pot/Pot", "@Potsanity - Dark Star Lords Mausoleum (1)/Room of Judgement Top Item Pot"}, -- [DSLM B-7] Room of Judgement Top Item Pot
    [430639] = {"@Dark Star Lords Mausoleum/Entrance Gate Item Pot/Pot", "@Potsanity - Dark Star Lords Mausoleum (4)/Entrance Gate Item Pot"}, -- [DSLM D-7] Entrance Gate Item Pot
    [430640] = {"@Dark Star Lords Mausoleum/Entrance Gate Coin Pot/Pot", "@Potsanity - Dark Star Lords Mausoleum (4)/Entrance Gate Coin Pot"}, -- [DSLM D-7] Entrance Gate Coin Pot
    [430641] = {"@Ancient Chaos/Soul Gate Item Pot/Pot", "@Potsanity - Ancient Chaos (5)/Soul Gate Item Pot"}, -- [AC C-1] Soul Gate Item Pot
    [430642] = {"@Ancient Chaos/Corridor of Blood Upper Coin Pot/Pot", "@Potsanity - Ancient Chaos (5)/Corridor of Blood Upper Coin Pot"}, -- [AC C-3] Corridor of Blood Upper Coin Pot
    [430643] = {"@Ancient Chaos/Corridor of Blood Right Coin Pot/Pot", "@Potsanity - Ancient Chaos (5)/Corridor of Blood Right Coin Pot"}, -- [AC C-3] Corridor of Blood Right Coin Pot
    [430644] = {"@Ancient Chaos/Ziggurat of Destiny Item Pot/Pot", "@Potsanity - Ancient Chaos (4)/Ziggurat of Destiny Item Pot"}, -- [AC D-3] Ziggurat of Destiny Item Pot
    [430645] = {"@Ancient Chaos/There is Nothing Here Coin Pot/Pot", "@Potsanity - Ancient Chaos (3)/There is Nothing Here Coin Pot"}, -- [AC A-4] There is Nothing Here Coin Pot
    [430646] = {"@Ancient Chaos/Grail Item Pot/Pot", "@Potsanity - Ancient Chaos (3)/Grail Item Pot"}, -- [AC B-4] Grail Item Pot
    [430647] = {"@Ancient Chaos/Pre-Secret Shortcut Item Pot/Pot", "@Potsanity - Ancient Chaos (4)/Pre-Secret Shortcut Item Pot"}, -- [AC C-4] Pre-Secret Shortcut Item Pot
    [430648] = {"@Ancient Chaos/Post-Secret Shortcut Item Pot/Pot", "@Potsanity - Ancient Chaos (4)/Post-Secret Shortcut Item Pot"}, -- [AC C-4] Post-Secret Shortcut Item Pot
    [430649] = {"@Ancient Chaos/Zhulong Blocked Item Pot/Pot", "@Potsanity - Ancient Chaos (4)/Zhulong Blocked Item Pot"}, -- [AC D-5] Zhulong Blocked Item Pot
    [430650] = {"@Ancient Chaos/Queen of the Night Weight Pot/Pot", "@Potsanity - Ancient Chaos (3)/Queen of the Night Weight Pot"}, -- [AC A-5] Queen of the Night Weight Pot
    [430651] = {"@Ancient Chaos/Queen of the Night Coin Pot/Pot", "@Potsanity - Ancient Chaos (3)/Queen of the Night Coin Pot"}, -- [AC A-5] Queen of the Night Coin Pot
    [430652] = {"@Ancient Chaos/Nine Eyes Wrong Side Coin Pot/Pot", "@Potsanity - Ancient Chaos (3)/Nine Eyes Wrong Side Coin Pot"}, -- [AC B-5] Nine Eyes Wrong Side Coin Pot
    [430653] = {"@Ancient Chaos/Shortcut Room Item Pot/Pot", "@Potsanity - Ancient Chaos (2)/Shortcut Room Item Pot"}, -- [AC C-5] Shortcut Room Item Pot
    [430654] = {"@Ancient Chaos/Shortcut Room Coin Pot/Pot", "@Potsanity - Ancient Chaos (2)/Shortcut Room Coin Pot"}, -- [AC C-5] Shortcut Room Coin Pot
    [430655] = {"@Ancient Chaos/Above Mantra Mural Item Pot/Pot", "@Potsanity - Ancient Chaos (4)/Above Mantra Mural Item Pot"}, -- [AC D-4] Above Mantra Mural Item Pot
    [430656] = {"@Ancient Chaos/Path to Inferno Coin Pot/Pot", "@Potsanity - Ancient Chaos (1)/Path to Inferno Coin Pot"}, -- [AC B-6] Path to Inferno Coin Pot
    [430657] = {"@Ancient Chaos/Entrance Gate Item Pot/Pot", "@Potsanity - Ancient Chaos (1)/Entrance Gate Item Pot"}, -- [AC D-6] Entrance Gate Item Pot
    [430658] = {"@Ancient Chaos/Annunaki Hot Spring Item Pot/Pot", "@Potsanity - Ancient Chaos (1)/Annunaki Hot Spring Item Pot"}, -- [AC D-7] Annunaki Hot Spring Item Pot
    [430659] = {"@Ancient Chaos/Annunaki Hot Spring Coin Pot/Pot", "@Potsanity - Ancient Chaos (1)/Annunaki Hot Spring Coin Pot"}, -- [AC D-7] Annunaki Hot Spring Coin Pot
    [430660] = {"@Hall of Malice/Below Entrance Gate Item Pot/Pot", "@Potsanity - Hall of Malice (1)/Below Entrance Gate Item Pot"}, -- [HOM C-1] Below Entrance Gate Item Pot
    [430661] = {"@Hall of Malice/Below Grail Coin Pot/Pot", "@Potsanity - Hall of Malice (1)/Below Grail Coin Pot"}, -- [HOM C-2] Below Grail Coin Pot
    [430662] = {"@Hall of Malice/Sphinx Room Coin Pot/Pot", "@Potsanity - Hall of Malice (2)/Sphinx Room Coin Pot"}, -- [HOM D-2] Sphinx Room Coin Pot
    [430663] = {"@Hall of Malice/Crusher Trap Hidden Coin Pot/Pot", "@Potsanity - Hall of Malice (2)/Crusher Trap Hidden Coin Pot"}, -- [HOM E-2] Crusher Trap Hidden Coin Pot
    [430664] = {"@Hall of Malice/Lernaean Hydra Room Coin Pot/Pot", "@Potsanity - Hall of Malice (1)/Lernaean Hydra Room Coin Pot"}, -- [HOM B-3] Lernaean Hydra Room Coin Pot
    [430665] = {"@Hall of Malice/Delphyne Room Coin Pot/Pot", "@Potsanity - Hall of Malice (2)/Delphyne Room Coin Pot"}, -- [HOM C-3] Delphyne Room Coin Pot
    [430666] = {"@Hall of Malice/Time Serdab Item Pot/Pot", "@Potsanity - Hall of Malice (3)/Time Serdab Item Pot"}, -- [HOM A-4] Time Serdab Item Pot
    [430667] = {"@Hall of Malice/Time Serdab Coin Pot/Pot", "@Potsanity - Hall of Malice (3)/Time Serdab Coin Pot"}, -- [HOM A-4] Time Serdab Coin Pot
    [430668] = {"@Hall of Malice/Nemean Lion Right Item Pot/Pot", "@Potsanity - Hall of Malice (1)/Nemean Lion Right Item Pot"}, -- [HOM B-4] Nemean Lion Right Item Pot
    [430669] = {"@Hall of Malice/Nemean Lion Left Coin Pot/Pot", "@Potsanity - Hall of Malice (1)/Nemean Lion Left Coin Pot"}, -- [HOM B-4] Nemean Lion Left Coin Pot
    [430670] = {"@Hall of Malice/Phaia Room Coin Pot/Pot", "@Potsanity - Hall of Malice (3)/Phaia Room Coin Pot"}, -- [HOM E-4] Phaia Room Coin Pot
    [430671] = {"@Hall of Malice/Fairylan Bottom Item Pot/Pot", "@Potsanity - Hall of Malice (3)/Fairylan Bottom Item Pot"}, -- [HOM G-4] Fairylan Bottom Item Pot
    [430672] = {"@Hall of Malice/Fairylan Left Coin Pot/Pot", "@Potsanity - Hall of Malice (2)/Fairylan Left Coin Pot"}, -- [HOM G-4] Fairylan Left Coin Pot
    [430673] = {"@Hall of Malice/Orthrus Third Coin Pot/Pot", "@Potsanity - Hall of Malice (4)/Orthrus Third Coin Pot"}, -- [HOM D-5] Orthrus Third Coin Pot
    [430674] = {"@Hall of Malice/Orthrus Approach Coin Pot/Pot", "@Potsanity - Hall of Malice (3)/Orthrus Approach Coin Pot"}, -- [HOM E-5] Orthrus Approach Coin Pot
    [430675] = {"@Hall of Malice/Corridor of Blood Coin Pot/Pot", "@Potsanity - Hall of Malice (2)/Corridor of Blood Coin Pot"}, -- [HOM F-5] Corridor of Blood Coin Pot
    [430676] = {"@Eternal Prison - Gloom/Gate with Glowing Eyes Item Pot/Pot", "@Potsanity - Eternal Prison - Gloom (2)/Gate with Glowing Eyes Item Pot"}, -- [EPG D-1] Gate with Glowing Eyes Item Pot
    [430677] = {"@Eternal Prison - Gloom/Second Hell Gate Approach Item Pot/Pot", "@Potsanity - Eternal Prison - Gloom (4)/Second Hell Gate Approach Item Pot"}, -- [EPG E-1] Second Hell Gate Approach Item Pot
    [430678] = {"@Eternal Prison - Gloom/Soul Gate Coin Pot/Pot", "@Potsanity - Eternal Prison - Gloom (2)/Soul Gate Coin Pot"}, -- [EPG D-2] Soul Gate Coin Pot
    [430679] = {"@Eternal Prison - Gloom/Right of Prison Cells Coin Pot/Pot", "@Potsanity - Eternal Prison - Gloom (4)/Right of Prison Cells Coin Pot"}, -- [EPG F-2] Right of Prison Cells Coin Pot
    [430680] = {"@Eternal Prison - Gloom/Under River Styx Item Pot/Pot", "@Potsanity - Eternal Prison - Gloom (2)/Under River Styx Item Pot"}, -- [EPG D-3] Under River Styx Item Pot
    [430681] = {"@Eternal Prison - Gloom/Under River Styx Coin Pot/Pot", "@Potsanity - Eternal Prison - Gloom (2)/Under River Styx Coin Pot"}, -- [EPG D-3] Under River Styx Coin Pot
    [430682] = {"@Eternal Prison - Gloom/Fifth Hell Gate Exit Coin Pot/Pot", "@Potsanity - Eternal Prison - Gloom (4)/Fifth Hell Gate Exit Coin Pot"}, -- [EPG E-3] Fifth Hell Gate Exit Coin Pot
    [430683] = {"@Eternal Prison - Gloom/Next to Grail Item Pot/Pot", "@Potsanity - Eternal Prison - Gloom (3)/Next to Grail Item Pot"}, -- [EPG D-4] Next to Grail Item Pot
    [430684] = {"@Eternal Prison - Gloom/Leap of Faith Item Pot/Pot", "@Potsanity - Eternal Prison - Gloom (3)/Leap of Faith Item Pot"}, -- [EPG D-4] Leap of Faith Item Pot
    [430685] = {"@Eternal Prison - Gloom/Mantra Mural Item Pot/Pot", "@Potsanity - Eternal Prison - Gloom (1)/Mantra Mural Item Pot"}, -- [EPG C-5] Mantra Mural Item Pot
    [430686] = {"@Eternal Prison - Gloom/Fourth Hell Gate Approach Item Pot/Pot", "@Potsanity - Eternal Prison - Gloom (3)/Fourth Hell Gate Approach Item Pot"}, -- [EPG D-5] Fourth Hell Gate Approach Item Pot
    [430687] = {"@Eternal Prison - Gloom/Below Garm Statue Coin Pot/Pot", "@Potsanity - Eternal Prison - Gloom (1)/Below Garm Statue Coin Pot"}, -- [EPG B-6] Below Garm Statue Coin Pot
    [430688] = {"@Eternal Prison - Gloom/Weapon Vault Item Pot #2/Pot", "@Potsanity - Eternal Prison - Gloom (1)/Weapon Vault Item Pot #2"}, -- [EPG C-6] Weapon Vault Item Pot #2
    [430689] = {"@Eternal Prison - Gloom/Weapon Vault Item Pot #1/Pot", "@Potsanity - Eternal Prison - Gloom (1)/Weapon Vault Item Pot #1"}, -- [EPG C-6] Weapon Vault Item Pot #1
    [430690] = {"@Eternal Prison - Gloom/Key Fairy Coin Pot/Pot", "@Potsanity - Eternal Prison - Gloom (3)/Key Fairy Coin Pot"}, -- [EPG D-6] Key Fairy Coin Pot
    [430691] = {"@Eternal Prison - Gloom/Key Fairy Item Pot/Pot", "@Potsanity - Eternal Prison - Gloom (3)/Key Fairy Item Pot"}, -- [EPG D-6] Key Fairy Item Pot
    [430692] = {"@Eternal Prison - Gloom/Software Mural Item Pot #1/Pot", "@Potsanity - Eternal Prison - Gloom (2)/Software Mural Item Pot #1"}, -- [EPG C-7] Software Mural Item Pot #1
    [430693] = {"@Eternal Prison - Gloom/Software Mural Item Pot #2/Pot", "@Potsanity - Eternal Prison - Gloom (1)/Software Mural Item Pot #2"}, -- [EPG C-7] Software Mural Item Pot #2
    [430694] = {"@Eternal Prison - Doom/Sixth Hell Gate Exit Item Pot/Pot", "@Potsanity - Eternal Prison - Doom (3)/Sixth Hell Gate Exit Item Pot"}, -- [EPD C-1] Sixth Hell Gate Exit Item Pot
    [430695] = {"@Eternal Prison - Doom/Sixth Hell Gate Exit Coin Pot/Pot", "@Potsanity - Eternal Prison - Doom (3)/Sixth Hell Gate Exit Coin Pot"}, -- [EPD C-1] Sixth Hell Gate Exit Coin Pot
    [430696] = {"@Eternal Prison - Doom/Seventh Hell Gate Approach Item Pot/Pot", "@Potsanity - Eternal Prison - Doom (2)/Seventh Hell Gate Approach Item Pot"}, -- [EPD C-2] Seventh Hell Gate Approach Item Pot
    [430697] = {"@Eternal Prison - Doom/Seventh Hell Gate Approach Coin Pot/Pot", "@Potsanity - Eternal Prison - Doom (2)/Seventh Hell Gate Approach Coin Pot"}, -- [EPD C-2] Seventh Hell Gate Approach Coin Pot
    [430698] = {"@Eternal Prison - Doom/Maze Clear Item Pot #2/Pot", "@Potsanity - Eternal Prison - Doom (1)/Maze Clear Item Pot #2"}, -- [EPD A-4] Maze Clear Item Pot #2
    [430699] = {"@Eternal Prison - Doom/Maze Clear Coin Pot/Pot", "@Potsanity - Eternal Prison - Doom (1)/Maze Clear Coin Pot"}, -- [EPD A-4] Maze Clear Coin Pot
    [430700] = {"@Eternal Prison - Doom/Maze Clear Item Pot #1/Pot", "@Potsanity - Eternal Prison - Doom (1)/Maze Clear Item Pot #1"}, -- [EPD A-4] Maze Clear Item Pot #1
    [430701] = {"@Eternal Prison - Doom/Sixth Hell Gate Approach Item Pot/Pot", "@Potsanity - Eternal Prison - Doom (2)/Sixth Hell Gate Approach Item Pot"}, -- [EPD E-4] Sixth Hell Gate Approach Item Pot
    [430702] = {"@Eternal Prison - Doom/Left Ladder Weight Pot/Pot", "@Potsanity - Eternal Prison - Doom (2)/Left Ladder Weight Pot"}, -- [EPD D-5] Left Ladder Weight Pot
    [430703] = {"@Eternal Prison - Doom/Yuga Wheel Coin Pot/Pot", "@Potsanity - Eternal Prison - Doom (2)/Yuga Wheel Coin Pot"}, -- [EPD D-5] Yuga Wheel Coin Pot
    [430704] = {"@Eternal Prison - Doom/Blikjandabol Lava Drop Coin Pot/Pot", "@Potsanity - Eternal Prison - Doom (1)/Blikjandabol Lava Drop Coin Pot"}, -- [EPD C-6] Blikjandabol Lava Drop Coin Pot
    [430705] = {"@Eternal Prison - Doom/Blikjandabol Lava Drop Item Pot/Pot", "@Potsanity - Eternal Prison - Doom (1)/Blikjandabol Lava Drop Item Pot"}, -- [EPD C-7] Blikjandabol Lava Drop Item Pot
    [430707] = {"@Valhalla/Mantra Mural Coin Pot/Pot", "@Potsanity - Valhalla (3)/Mantra Mural Coin Pot"}, -- [VAL D-1] Mantra Mural Coin Pot
    [430708] = {"@Immortal Battlefield/Corona Arsenal Left Item Pot/Pot", "@Potsanity - Immortal Battlefield (5)/Corona Arsenal Left Item Pot"}, -- [IB I-6] Corona Arsenal Left Item Pot
    [430713] = {"@Ancient Chaos/Abandon Your Desires Coin Pot #1/Pot", "@Potsanity - Ancient Chaos (1)/Abandon Your Desires Coin Pot #1"}, -- [AC B-6] Abandon Your Desires Coin Pot #1
    [430714] = {"@Ancient Chaos/Abandon Your Desires Coin Pot #2/Pot", "@Potsanity - Ancient Chaos (2)/Abandon Your Desires Coin Pot #2"}, -- [AC B-6] Abandon Your Desires Coin Pot #2
    [430715] = {"@Ancient Chaos/Abandon Your Desires Coin Pot #3/Pot", "@Potsanity - Ancient Chaos (2)/Abandon Your Desires Coin Pot #3"}, -- [AC B-6] Abandon Your Desires Coin Pot #3
    [430716] = {"@Ancient Chaos/Abandon Your Desires Coin Pot #4/Pot", "@Potsanity - Ancient Chaos (2)/Abandon Your Desires Coin Pot #4"}, -- [AC B-6] Abandon Your Desires Coin Pot #4
}
